# Práctica 2: Introducción a N-dimensional arrays en Python 

## Introducción a NumPy N-dimensional arrays (ndarray para abreviar)

[The N-dimensional array](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html)

**ndarray** es la forma más usual para almacenar datos y trabajar con ellos
 en el módulo numpy de Python.

 Para fijar ideas, podemos imaginar que un **ndarray** es simplemente un vector 
 o una matriz.

 Veamos cómo se crea un **ndarray**

In [12]:
# importamos el módulo numpy the Python

import numpy as np

In [13]:
# definimos un vector de 3 componentes (1d-array)
x = np.array([1, 4, 3])
print(x)
print(type(x)) # tipo de dato

# veamos algunos atributos (características) del array
print(x.shape) # forma o dimensión del array
print(x.size)  # tamaño del array
print(x.dtype) # tipo de datos que contiene


[1 4 3]
<class 'numpy.ndarray'>
(3,)
3
int64


In [14]:
# definimos un matriz (2d-array)
y = np.array([[1, 4, 3], [9, 2, 7]])
print(y)
print(type(y)) # tipo de dato

# veamos algunos **atributos** (características) del array
print(y.shape) # forma o dimensión del array
print(y.size)  # tamaño del array
print(y.dtype) # tipo de datos que contiene


[[1 4 3]
 [9 2 7]]
<class 'numpy.ndarray'>
(2, 3)
6
int64


Algunas funciones usuales para crear un ndarray son:

In [15]:
# array de ceros de tamaño especificado
a = np.zeros([3,3])
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
# array de unos de tamaño especificado
b = np.ones([5])
print(b)


[1. 1. 1. 1. 1.]


In [17]:
# array donde se especifica el inicio, el final (no incluido) y el paso
c = np.arange(1, 5, 0.5)
print(c)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [25]:
# para el caso de que el array contenga números complejos
array_complex = 1j * np.arange(5)
print(array_complex)

# otro ejemplo
z = np.ones(4, dtype=complex)*2 
print(z)

[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[2.+0.j 2.+0.j 2.+0.j 2.+0.j]


In [18]:
# array donde se especifica el inicio, final (incluido) y el número de 
# elementos equiespaciados
d = np.linspace(0, 1, 10)
print(d)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


Combinando ndarrays: Apilamiento (**stack**) horizontal y vertical.

En muchas ocasiones es necesario apilar datos de forma horizontal o vertical.

In [21]:
# creamos un primer array
a1 = np.array([1, 2, 3])
print(a1)
# creamos un segundo array
a2 = np.array([4, 5, 6])
print(a2)
# vertical stack (apilamiento vertical)
a3 = np.vstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


In [22]:
# horizontal stack (apilamiento horizontal)
a4 = np.hstack((a1, a2))
print(a4)
print(a4.shape)

[1 2 3 4 5 6]
(6,)


En ocasiones, los datos a estudiar aparecen en otra estructura de datos, por 
ejemplo en el tipo **lista** . Las listas son colecciones indexadas de datos.
Se escriben entre corchetes con sus elementos separados por comas. 

Para **transformar una lista en un ndarray** :

In [ ]:
lista = [1, 2, 3] # esto es una lista en Python
print(lista)
print(type(lista))

vector = np.array(lista) # convertimos la lista en un 1d-array (vector)
print(vector)
print(type(vector))

[1, 2, 3]
<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
# Otra lista (de lista) de datos
data = [[11, 22],
[33, 44],
[55, 66]]
print(data)
print(type(data))

# convertimos la lista en un 2d-array (matriz)
data = np.array(data)
print(data)
print(type(data))
print(data.shape)

[[11, 22], [33, 44], [55, 66]]
<class 'list'>
[[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>
(3, 2)


Otro tipo de datos son las **tuplas**. Muy similares a las listas, pero una vez 
creada una tupla, sus elem,entos no se pueden cambiar. Las tuplas son inmutables.
Se escriben entre paréntesis con sus elementos separados por comas 

Para **transformar tuplas en ndarrays** : 

In [26]:
tupla = (1, 2, 3) # esto es una tupla en Python
print(tupla)
print(type(tupla))

vector = np.array(tupla) # convertimos la tupla en un 1d-array (vector)
print(vector)
print(type(vector))

(1, 2, 3)
<class 'tuple'>
[1 2 3]
<class 'numpy.ndarray'>
