# Práctica 5. Matrices: aritmética y norma 

In [17]:
import numpy as np

## Aritmética básica de matrices

In [18]:
# Introducimos dos matrices como 2d numpy array

A = np.array([
    [1, 3, 5],
    [7, 9, 11]]
    )
print(f"A =  {A}")
B = np.array([
    [0, 2, 4],
    [6, 8, 10]]
    )
print(f"B = {B}")

A =  [[ 1  3  5]
 [ 7  9 11]]
B = [[ 0  2  4]
 [ 6  8 10]]


In [19]:
# suma y resta de matrices
C = A + B
print(f"A + B = \n {C}")
D = A - B
print(f"A - B = \n {D}")

A + B = 
 [[ 1  5  9]
 [13 17 21]]
A - B = 
 [[1 1 1]
 [1 1 1]]


In [20]:
# producto de matrices con .dot. También se puede hacer con el operador @
A = np.array([ 
    [1, 2],
    [3, 4],
    [5, 6]]
)
B = np.array([
    [1, 2],
    [3, 4]]
)
C = A.dot(B)
print(f"A*B = \n {C}")
D = A @ B
print(f"A*B = \n {D}")


A*B = 
 [[ 7 10]
 [15 22]
 [23 34]]
A*B = 
 [[ 7 10]
 [15 22]
 [23 34]]


In [21]:
# Producto matriz-vector (igual que producto de matrices)
# ojo con las dimensiones!!
A = np.array([ 
    [1, 2],
    [3, 4],
    [5, 6]]
)
b = np.array([0.5, 0.5])
print(f"A*b = {A.dot(b)}")
print(f"A*b = {A @ b}")

A*b = [1.5 3.5 5.5]
A*b = [1.5 3.5 5.5]


In [22]:
# Producto matriz-escalar con operador *
A = np.array([ 
    [1, 2],
    [3, 4],
    [5, 6]]
)
b = 0.5
print(f"Ab = \n {A * b}")

Ab = 
 [[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]


In [23]:
# Producto (Hadamard) y división de matrices componente a componente
A = np.array([
    [1, 3, 5],
    [7, 9, 11]]
    )
B = np.array([
    [1, 2, 4],
    [6, 8, 10]]
    )
print(f"(Producto de Hadamard) A ◦ B = \n {A * B}")
print(f"A / B = \n {A / B}")

(Producto de Hadamard) A ◦ B = 
 [[  1   6  20]
 [ 42  72 110]]
A / B = 
 [[1.         1.5        1.25      ]
 [1.16666667 1.125      1.1       ]]


## Algunos tipos de matrices:
##    a) Simétricas
##    b) Triangulares superior e inferior
##    c) Diagonales

In [24]:
A = np.array([
    [2, -1, 0],
    [-1, 2, -1],
    [0, -1, 2]]
)
print(f"A = {A}")
# calculamos la traspuesta de A
B = A.T
print(f"A^T = {B}")
# preguntamos si A coincide con su traspuesta
A == B

A = [[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]
A^T = [[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Calculamos las partes triangular inferior y superior de A.


In [25]:

A = np.array([
    [2, -1, 0],
    [-1, 2, -1],
    [0, -1, 2]]
)
# triangular inferior
L = np.tril(A)
print(f"triangular inferior de A = {L}")

# triangular superior
U = np.triu(A)
print(f"triangular superior de A = {U}")



triangular inferior de A = [[ 2  0  0]
 [-1  2  0]
 [ 0 -1  2]]
triangular superior de A = [[ 2 -1  0]
 [ 0  2 -1]
 [ 0  0  2]]


extraemos la diagonal de A para generar una matriz diagonal

In [26]:
d = np.diag(A) # vector que contiene la diagonal de A
print(f"diagonal = {d}")
D = np.diag(d) # matriz con la diagonal de A
print(f"D = {D}")

diagonal = [2 2 2]
D = [[2 0 0]
 [0 2 0]
 [0 0 2]]


Matriz identidad

In [27]:
I = np.identity(3)
print(f"I_3 = {I}")

I_3 = [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Inversa, traza, determinante y rango

In [28]:
A = np.array([
    [2, -1, 0],
    [-1, 2, -1],
    [0, -1, 2]]
)
B = np.linalg.inv(A) # inversa
print(f"inversa de A: \n {B}")
print(f"comprobación: \n {A @ B}")

# traza de A
print(f"traza de A = {np.trace(A)}")

# determinante de A (está en el submódulo de álgebra lineal)
print(f"determinante de A = {np.linalg.det(A)}")

# rango de A
print(f"rango de A = {np.linalg.matrix_rank(A)}")

inversa de A: 
 [[0.75 0.5  0.25]
 [0.5  1.   0.5 ]
 [0.25 0.5  0.75]]
comprobación: 
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00]]
traza de A = 6
determinante de A = 4.0
rango de A = 3


## [Normas de matrices](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html)

Se pueden definir varias normas para matrices. Quizás, la más habitual es la 
llamada norma de Frobenius, la cual se define como
$\Vert A\Vert_F = \left(\sum_{i,j}a_{ij}^2 \right)^{1/2} $,
siendo $A=(a_{ij})$

In [29]:
A = np.array([
    [2, -1, 0],
    [-1, 2, -1],
    [0, -1, 2]]
)

print(f"A = \n {A}")

fro_A = np.linalg.norm(A, "fro") # norma de Frobenius
print(f"norma de Frobenius de A = {fro_A}")

A = 
 [[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]
norma de Frobenius de A = 4.0


### [Número de condicionamiento de una matriz](https://numpy.org/doc/stable/reference/generated/numpy.linalg.cond.html)

Para una matriz invertible $A$, el número de condicionamiento de $A$ se define 
como $c(A) = \Vert A\Vert\Vert A^{-1}\Vert$. Este número juega un papel esencial 
en el análisis de errores en la resolución de sistemas lineales de ecuaciones.

In [30]:
# cálculo del número de condicionamiento
A = np.array([
    [2, -1, 0],
    [-1, 2, -1],
    [0, -1, 2]]
)

print(f"A = \n {A}")

print(f"número de condicionamiento de A = {np.linalg.cond(A, 'fro')}")
# Nótese que hemos de especificar la norma usada para calcular el 
# número de condicionamiento


A = 
 [[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]
número de condicionamiento de A = 7.211102550927978


7.211102550927978

In [31]:
# En efecto: un cálculo directo muestra
np.linalg.norm(A, "fro") * np.linalg.norm(np.linalg.inv(A), "fro")

7.211102550927978