# Práctica 10. Factorización QR. Cálculo de autovalores y autovectores

In [2]:
import numpy as np

## Factorización QR

Dada una matriz $A$ de tamaño $m\times n$, con $m\geq n$, la factorización 
$QR$ expresa $A$ en la forma $A = QR$, donde $Q$ es una matriz ortogonal 
de tamaño $m\times m$ (sus columnas son vectores ortonormales; 
se cumple $Q^{-1} = Q^T$)  y $R$ es una matriz triangular superior de 
tamaño $m\times n$.

Más información en [numpy.linalg.qr() API.](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.qr.html)

In [3]:
# Veamos un ejemplo concreto

A = np.random.randn(4, 3)

print(f"A = {A}")

Q, R = np.linalg.qr(A)

print(f"Q =  {Q}")
print(f"R = {R}")

A = [[-0.37771645  0.17867731  0.84476089]
 [-1.02001871 -0.26860257 -0.1750103 ]
 [-0.35300527  1.42150948 -2.04161073]
 [ 0.68452971 -0.65106404 -0.85245058]]
Q =  [[-0.28340503  0.01410828  0.45719824]
 [-0.76533186 -0.46381376 -0.44619173]
 [-0.26486395  0.85148277 -0.43302679]
 [ 0.51361058 -0.24424341 -0.63590133]]
R = [[ 1.33277962 -0.55596793 -0.00254708]
 [ 0.          1.49651133 -1.43710062]
 [ 0.          0.          1.89045795]]


In [4]:
# Comprobamos que A = QR

np.allclose(A, np.dot(Q, R))

True

In [5]:
# Veamos distintas formas de la factorización QR
# mode : {‘reduced’, ‘complete’, ‘r’, ‘raw’, ‘full’, ‘economic’}


Q, R = np.linalg.qr(A, mode='complete')

print(f"Q =  {Q}")
print(f"R = {R}")

Q =  [[-0.28340503  0.01410828  0.45719824  0.84288333]
 [-0.76533186 -0.46381376 -0.44619173 -0.00754222]
 [-0.26486395  0.85148277 -0.43302679  0.13157498]
 [ 0.51361058 -0.24424341 -0.63590133  0.52170761]]
R = [[ 1.33277962 -0.55596793 -0.00254708]
 [ 0.          1.49651133 -1.43710062]
 [ 0.          0.          1.89045795]
 [ 0.          0.          0.        ]]


## Cálculo de autovalores y autovectores

Dada una matriz cuadrada $A$ buscamos vectores no nulos $v$ y escalares 
$\lambda$  que cumplan $Av = \lambda v$. Los escalares $\lambda$ son 
los autovaloes y los vectores asociados $v$ los autovectores. 

En algunos casos importantes, por ejemplo cuando $A$ es simétrica, obtenemos la 
factorización $A = Q \Lambda Q^{-1}$, donde $Q$ almacena en sus columnas los 
autovectores y $\Lambda$ es una matriz diagonal que contiene los autovalores de 
$A$ en su diagonal.

Más información sobre su implementación en Python en 
[numpy.linalg.eig() API](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.eig.html)


In [6]:
# Veamos cómo se calculan los autovalores y autovectores

from numpy.linalg import eig

A = np.array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(f"A = {A}")

autovalores, autovectores = eig(A) # autovalores y  autovectores unitarios

print(f"autovalores = {autovalores}")
print(f"autovectores = \n {autovectores}")


A = [[1 2 3]
 [4 5 6]
 [7 8 9]]
autovalores = [ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]
autovectores = 
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [7]:
# En efecto, para el primer autovalor tenemos:
B = A.dot(autovectores[:, 0])
print(B)
C = autovectores[:, 0] * autovalores[0]
print(C)

# y lo mismo para los otros dos:
B = A.dot(autovectores[:, 1])
print(B)
C = autovectores[:, 1] * autovalores[1]
print(C)

B = A.dot(autovectores[:, 2])
print(B)
C = autovectores[:, 2] * autovalores[2]
print(C)



[ -3.73863537  -8.46653421 -13.19443305]
[ -3.73863537  -8.46653421 -13.19443305]
[ 0.87764976  0.09688771 -0.68387434]
[ 0.87764976  0.09688771 -0.68387434]
[-4.4408921e-16 -4.4408921e-16 -8.8817842e-16]
[-3.98417052e-16  7.96834105e-16 -3.98417052e-16]


In [8]:
# En este caso, la matriz A es diagonalizable (autovalores reales y distintos)
# Por tanto, A admite la factorización anterior
from numpy.linalg import inv

Q = autovectores
print(f"Q = \n {Q}")

L = np.diag(autovalores)
print(f"L = \n {L}")

inv_Q = inv(Q)
print(f"inversa de Q = \n {inv_Q}")



print(f"Q L inv(Q) = \n {Q.dot(L).dot(inv_Q)}")

Q = 
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
L = 
 [[ 1.61168440e+01  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.11684397e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -9.75918483e-16]]
inversa de Q = 
 [[-0.48295226 -0.59340999 -0.70386772]
 [-0.91788599 -0.24901003  0.41986593]
 [ 0.40824829 -0.81649658  0.40824829]]
Q L inv(Q) = 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### Método de factorización $QR$ para el cálculo de autovalores

In [9]:

from numpy.linalg import qr

A = np.array([[0, 2], 
              [2, 3]])

Q, R = qr(A)

print('Q = \n', Q)
print('R = \n', R)

B = np.dot(Q, R)
print('QR = \n', B)


p = [1, 5, 10, 20, 40]
for i in range(40):
    Q, R = qr(A)
    A = np.dot(R, Q)
    if i+1 in p:
        print(f'Iteración {i+1}:')
        print(f"A = {A}")
        print(f"Q = {Q}")
# los autovalores quedan almacenados en la diagonal de A
# los autovectores en las columnas de Q

Q = 
 [[ 0. -1.]
 [-1.  0.]]
R = 
 [[-2. -3.]
 [ 0. -2.]]
QR = 
 [[0. 2.]
 [2. 3.]]
Iteración 1:
A = [[3. 2.]
 [2. 0.]]
Q = [[ 0. -1.]
 [-1.  0.]]
Iteración 5:
A = [[ 3.99998093  0.00976559]
 [ 0.00976559 -0.99998093]]
Q = [[-0.99995232 -0.00976531]
 [-0.00976531  0.99995232]]
Iteración 10:
A = [[ 4.00000000e+00  9.53674316e-06]
 [ 9.53674316e-06 -1.00000000e+00]]
Q = [[-1.00000000e+00 -9.53674316e-06]
 [-9.53674316e-06  1.00000000e+00]]
Iteración 20:
A = [[ 4.00000000e+00  9.09482285e-12]
 [ 9.09494702e-12 -1.00000000e+00]]
Q = [[-1.00000000e+00 -9.09494702e-12]
 [-9.09494702e-12  1.00000000e+00]]
Iteración 40:
A = [[ 4.00000000e+00 -1.24167008e-16]
 [ 8.27180613e-24 -1.00000000e+00]]
Q = [[-1.00000000e+00 -8.27180613e-24]
 [-8.27180613e-24  1.00000000e+00]]


In [10]:
# En efecto:

autovalores, autovectores = eig(A) # autovalores y  autovectores unitarios

print(f"autovalores = {autovalores}")
print(f"autovectores = \n {autovectores}")

autovalores = [ 4. -1.]
autovectores = 
 [[1.00000000e+00 2.48334016e-17]
 [0.00000000e+00 1.00000000e+00]]
