# Examen de prácticas. Convocatoria Enero 2024

Francisco Javier Mercader Martínez

## Descomposición polar de una matriz

Como bien sabemos, todo número complejo $z$ se puede expresar en la forma $z=re^{j\theta}$, donde $r\ge0$ y $e^{j\theta}$ es un punto del círculo de la unidad. De manera similar, toda matriz cuadrada $A$ admite una factorización de la forma $$A=QS$$ donde $Q$ es una matriz ortogonal (análogo al $e^{j\theta}$), y $S$ es una matriz simétrica y semidefinida positiva (análogo a $r$).

Esta factorización se llama **descomposición polar**. Se utilzia frecuentemente en Mecánica de Sólidos, donde la matriz $A$ representa la deformación de un sólido, la cual se descompone en una rotación ($Q$) y unos estiramiento (o alargamientos) ($S$). También tiene aplicaciones en una parte de la Ciencia de Datos llamada Geometric Deep Learning.

La factorización polar se puede calcular muy fácilmente a partir de la factorización SVD. En efecto, se tiene que: $$A=U\Sigma V^\intercal=(UV^\intercal)(V\Sigma V^\intercal)=(Q)(S),$$es decir $Q=UV^\intercal$ y $S=V\Sigma V^\intercal$.

En este ejercicio calcularemos la factorización polar de una matriz dada usando estas ideas.

Introduce una matriz aleatoria de tamaño $3\times3$ y llámala $A$. Imprime la matriz $A$ y el tipo de datos que contiene.

In [15]:
import numpy as np

In [16]:
A = np.random.randn(3, 3)
print(f"A = \n {A}")
print(f"Tipo de datos de A: {A.dtype}")

A = 
 [[-0.03776647  0.77495791  1.50822007]
 [-0.26858041 -0.78602587  1.12848732]
 [-0.14770274 -1.1515381  -0.80360214]]
Tipo de datos de A: float64


Calcula la factorización SVD de $A$. Imprime las matrices $U,\,\Sigma$ y $V^\intercal$

In [17]:
from scipy.linalg import svd

U, s, V = svd(A)

# creamos una matriz de zeros de tamaño m x n 
Sigma = np.zeros((A.shape[0], A.shape[1]))

# rellenamos Sigma con las valores singulares
Sigma[:A.shape[0], :A.shape[0]] = np.diag(s)

print(f"U = \n {U}")
print(f"S = \n {Sigma}")
print(f"V^T = {V}")

U = 
 [[-0.77151858  0.01421749 -0.63604791]
 [-0.28919207  0.88265819  0.37051649]
 [ 0.56668071  0.46980037 -0.67687561]]
S = 
 [[2.19812398 0.         0.        ]
 [0.         1.41471688 0.        ]
 [0.         0.         0.0250833 ]]
V^T = [[ 0.01051286 -0.46545892 -0.88500705]
 [-0.21699921 -0.86502625  0.45237255]
 [ 0.97611517 -0.1872901   0.11009811]]


Calcula la descomposición polar de $A$ según se ha explicado anteriormente. Has de imprimir las matrices $Q$ y $S$ y comprobar que, salvo errores de redondeo/representación, se cumple que $A=QS$ 

In [18]:
Q = U.dot(V)

# Como la matriz V que obtenemos ya es la traspuesta, para calcular S, debemos
# multiplicar V.T * Sigma * V 

S = V.T.dot(Sigma.dot(V))

print(f"Q = \n {Q}")
print(f"S = \n {S}")

print(f'A = Q · S: {np.all(np.round(A) == np.round(Q.dot(S)))}')

Q = 
 [[-0.63205206  0.46593718  0.61920331]
 [ 0.16709041 -0.69830955  0.69602053]
 [-0.75669742 -0.54338414 -0.36351435]]
S = 
 [[ 0.09075945  0.25021479 -0.15663053]
 [ 0.25021479  1.53569861  0.35136699]
 [-0.15663053  0.35136699  2.01146611]]
A = Q · S: True


Se puede demostrar que la matriz $Q$ de la descomposición polar es la matriz ortogonal más próxima a $A$ para la norma de Frobenius, es decir, dada $A$ la solución del problema $$\text{Minimizar }\|A-Z\|$$entre todas las matrices ortogonales, $Z$, tiene como solución $Z=Q$.

A continuación haremos una pequña comprobación de este hecho. Se pide:

1. Introduce **en formato sparse** la siguiente matriz $$Z=\begin{bmatrix}0.8 & 0.6 & 0\\ -0.6 & 0.8 & 0\\ 0 & 0 & 1\end{bmatrix}$$ e imprímela tanto en formato sparse como dense.

In [19]:
from scipy.sparse import csr_matrix

Z_sparse = csr_matrix([
    [0.8, 0.6, 0],
    [-0.6, 0.8, 0],
    [0, 0, 1]
])
Z_dense = Z_sparse.todense()

print(f"Z en formato sparse: \n {Z_sparse}")
print(f"Z en formato dense: \n {Z_dense}")



Z en formato sparse: 
   (0, 0)	0.8
  (0, 1)	0.6
  (1, 0)	-0.6
  (1, 1)	0.8
  (2, 2)	1.0
Z en formato dense: 
 [[ 0.8  0.6  0. ]
 [-0.6  0.8  0. ]
 [ 0.   0.   1. ]]


2. Comprueba que $Z$ es ortogonal. Justifica la respuesta haciendo uso de la inversa de $Z$

In [20]:
Z_inv = np.linalg.inv(Z_dense)

# Z es ortogonal si Z^-1 = Z^T

print(f"Z es ortogonal: {np.all(np.round(Z_inv) == np.round(Z_dense.T))}")

Z es ortogonal: True


Comprueba que, para la norma de Frobenius, se cumple que $$\|A-Q\|<\|A-Z\|$$

In [21]:
# La norma de Frobenius es la normal infinito
norma_AQ = np.linalg.norm(A - Q, ord=np.inf)

norma_AZ = np.linalg.norm(A - Z_dense, ord=np.inf)

print(f'||A - Q|| < ||A - Z||: {norma_AQ < norma_AZ}')

||A - Q|| < ||A - Z||: True
