# Examen de prácticas. Convocatoria Enero 2024

Francisco Javier Mercader Martínez

## Descomposición polar de una matriz

Como bien sabemos, todo número complejo $z$ se puede expresar en la forma $z=re^{j\theta}$, donde $r\ge0$ y $e^{j\theta}$ es un punto del círculo de la unidad. De manera similar, toda matriz cuadrada $A$ admite una factorización de la forma $$A=QS$$ donde $Q$ es una matriz ortogonal (análogo al $e^{j\theta}$), y $S$ es una matriz simétrica y semidefinida positiva (análogo a $r$).

Esta factorización se llama **descomposición polar**. Se utilzia frecuentemente en Mecánica de Sólidos, donde la matriz $A$ representa la deformación de un sólido, la cual se descompone en una rotación ($Q$) y unos estiramiento (o alargamientos) ($S$). También tiene aplicaciones en una parte de la Ciencia de Datos llamada Geometric Deep Learning.

La factorización polar se puede calcular muy fácilmente a partir de la factorización SVD. En efecto, se tiene que: $$A=U\Sigma V^\intercal=(UV^\intercal)(V\Sigma V^\intercal)=(Q)(S),$$es decir $Q=UV^\intercal$ y $S=V\Sigma V^\intercal$.

En este ejercicio calcularemos la factorización polar de una matriz dada usando estas ideas.

Introduce una matriz aleatoria de tamaño $3\times3$ y llámala $A$. Imprime la matriz $A$ y el tipo de datos que contiene.

In [50]:
import numpy as np

In [51]:
A = np.random.randn(3, 3)
print(f"A = \n {A}")
print(f"Tipo de datos de A: {A.dtype}")

A = 
 [[ 0.75912448  1.33334534 -1.51171182]
 [-0.47544692  0.45912062  1.00234749]
 [-2.83662965 -0.54552372 -0.44123745]]
Tipo de datos de A: float64


Calcula la factorización SVD de $A$. Imprime las matrices $U,\,\Sigma$ y $V^\intercal$

In [52]:
from scipy.linalg import svd

U, s, V = svd(A)

# creamos una matriz de zeros de tamaño m x n 
Sigma = np.zeros((A.shape[0], A.shape[1]))

# rellenamos Sigma con las valores singulares
Sigma[:A.shape[0], :A.shape[0]] = np.diag(s)

print(f"U = \n {U}")
print(f"S = \n {Sigma}")
print(f"V^T = {V}")

U = 
 [[-0.42591175 -0.83950484 -0.3373882 ]
 [ 0.13634739  0.30908791 -0.94120883]
 [ 0.89443198 -0.4468739  -0.01717987]]
S = 
 [[3.11333721 0.         0.        ]
 [0.         1.98150664 0.        ]
 [0.         0.         1.00020581]]
V^T = [[-0.93960855 -0.31902147  0.12393981]
 [ 0.24394175 -0.37025408  0.89632825]
 [ 0.24005874 -0.87243178 -0.42571656]]


Calcula la descomposición polar de $A$ según se ha explicado anteriormente. Has de imprimir las matrices $Q$ y $S$ y comprobar que, salvo errores de redondeo/representación, se cumple que $A=QS$ 

In [53]:
Q = U.dot(V)

# Como la matriz V que obtenemos ya es la traspuesta, para calcular S, debemos
# multiplicar V.T * Sigma * V 

S = V.T.dot(Sigma.dot(V))

print(f"Q = \n {Q}")
print(f"S = \n {S}")

print(f'A = Q · S: {np.all(np.round(A) == np.round(Q.dot(S)))}')

Q = 
 [[ 0.11440706  0.74105328 -0.66162759]
 [-0.27865913  0.66320169  0.69463127]
 [-0.95355132 -0.10489785 -0.28237622]]
S = 
 [[ 2.92420877  0.54479083 -0.03152124]
 [ 0.54479083  1.34979377 -0.40921559]
 [-0.03152124 -0.40921559  1.82104712]]
A = Q · S: True


Se puede demostrar que la matriz $Q$ de la descomposición polar es la matriz ortogonal más próxima a $A$ para la norma de Frobenius, es decir, dada $A$ la solución del problema $$\text{Minimizar }\|A-Z\|$$entre todas las matrices ortogonales, $Z$, tiene como solución $Z=Q$.

A continuación haremos una pequña comprobación de este hecho. Se pide:

1. Introduce **en formato sparse** la siguiente matriz $$Z=\begin{bmatrix}0.8 & 0.6 & 0\\ -0.6 & 0.8 & 0\\ 0 & 0 & 1\end{bmatrix}$$ e imprímela tanto en formato sparse como dense.

In [54]:
from scipy.sparse import csr_matrix

Z = np.array([
    [0.8, 0.6, 0],
    [-0.6, 0.8, 0],
    [0, 0, 1]
])

Z_sparse = csr_matrix(Z)
Z_dense = Z_sparse.todense()

print(f"Z en formato sparse: \n {Z_sparse}")
print(f"Z en formato dense: \n {Z_dense}")



Z en formato sparse: 
   (0, 0)	0.8
  (0, 1)	0.6
  (1, 0)	-0.6
  (1, 1)	0.8
  (2, 2)	1.0
Z en formato dense: 
 [[ 0.8  0.6  0. ]
 [-0.6  0.8  0. ]
 [ 0.   0.   1. ]]
Z es ortogonal: True


2. Comprueba que $Z$ es ortogonal. Justifica la respuesta haciendo uso de la inversa de $Z$

In [57]:
Z_inv = np.linalg.inv(Z)

# Z es ortogonal si Z^-1 = Z^T

print(f"Z es ortogonal: {np.all(np.round(Z_inv) == np.round(Z.T))}")

Z es ortogonal: True


Comprueba que, para la norma de Frobenius, se cumple que $$\|A-Q\|<\|A-Z\|$$

In [58]:
# La norma de Frobenius es la normal infinito
norma_AQ = np.linalg.norm(A - Q, ord=np.inf)

norma_AZ = np.linalg.norm(A - Z, ord=np.inf)

print(f'||A - Q|| < ||A - Z||: {norma_AQ < norma_AZ}')

||A - Q|| < ||A - Z||: True
