# Práctica 5: Ejercicio para entregar. 
## Dot Product Similarity Matrix

Una clase de matrices que aparencen de manera recurrente en varias aplicaciones
de Machine Learning son matrices S que toman la forma $S = DD^T$, donde D es una 
matriz de datos de tamaño $nxd$ y $D^T$ es su traspuesta.
En este ejercicio practicaremos el manejo de este tipo de matrices haciendo uso 
del módulo Numpy de Python. 

Introduce una matriz D de 4 filas y 8 columnas de modo que la primera fila 
contenga tu número de DNI y el resto de filas números de DNI de algunos 
familiares tuyos.
Imprime también por pantalla la matriz D

In [1]:
import numpy as np

In [2]:
# Completar aquí
D = np.array([
    [2, 6, 6, 4, 9, 1, 1, 0],
    [2, 2, 9, 8, 5, 6, 3, 0],
    [2, 2, 9, 9, 0, 7, 1, 3],
    [2, 6, 6, 4, 9, 1, 1, 2]]
)
print(f"D = \n {D}")
# --------------------


D = 
 [[2 6 6 4 9 1 1 0]
 [2 2 9 8 5 6 3 0]
 [2 2 9 9 0 7 1 3]
 [2 6 6 4 9 1 1 2]]


Calcula, usando las dos formas estudiadas en clase, e imprime por pantalla 
la matriz $S = DD^T$

In [3]:
# Completar aquí
Dt = D.T
s = D.dot(Dt)
print(f"S = \n {s}")
# --------------------


S = 
 [[175 156 114 175]
 [156 223 206 156]
 [114 206 229 120]
 [175 156 120 179]]


Introduce un vector b no nulo de dimensión 4, el que quieras, y calcula, de las 
dos formas que vimos en clase, el producto de S y b, es decir, S*b.
Calcula también b*S. Compara los resultados de S*b y b*S. 
¿Qué explicación encuentras de ambos resultados? 

In [5]:
# Completar aquí
b = np.array([1, 2, 3, 4])
Sb = s.dot(b)
bS = b @ s
print(f"Sb = \n {Sb}")
print(f"bS = \n {bS}")
Sb == bS
# En ambos casos el resultado es el mismo porque en el ordenador da igual el 
# orden, pues se van a calcular igual.
# --------------------


Sb = 
 [1529 1844 1693 1563]
bS = 
 [1529 1844 1693 1563]


array([ True,  True,  True,  True])

Introduce un escalar a, número real, y calcula a*S

In [ ]:
# Completar aquí
a = 5
aS = a * s
print(f"a · S = \n {aS}")
# --------------------


a · S = 
 [[ 875  780  570  875]
 [ 780 1115 1030  780]
 [ 570 1030 1145  600]
 [ 875  780  600  895]]


Calcula el producto de Hadamard de S y S. 
Calcula, componente a componente de S dividido por S.

In [ ]:
# Completar aquí
print(f"S · S = \n {s**2}")
print(f"S / S = \n {s / s}")
# --------------------


S · S = 
 [[30625 24336 12996 30625]
 [24336 49729 42436 24336]
 [12996 42436 52441 14400]
 [30625 24336 14400 32041]]
S / S = 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Comprueba que S es simétrica utilizando un operador Booleano

In [ ]:
# Completar aquí
st = s.T
print(f"S^T = \n {st}")
s == st
# La matriz S es simétrica porque coincide con su traspuesta.
# --------------------


S^T = 
 [[175 156 114 175]
 [156 223 206 156]
 [114 206 229 120]
 [175 156 120 179]]


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

Calcula las partes triangular inferior y superior de D.


In [ ]:

# Completar aquí
L = np.tril(D)
print(f"Triangular inferior de D = \n {L}")
U = np.triu(D)
print(f"Triangular superior de D = \n {U}")
# --------------------


Triangular inferior de D = 
 [[2 0 0 0 0 0 0 0]
 [2 2 0 0 0 0 0 0]
 [2 2 9 0 0 0 0 0]
 [2 6 6 4 0 0 0 0]]
Triangular superior de D = 
 [[2 6 6 4 9 1 1 0]
 [0 2 9 8 5 6 3 0]
 [0 0 9 9 0 7 1 3]
 [0 0 0 4 9 1 1 2]]


Extrae la diagonal de S y genera una matriz diagonal con la diagonal de S

In [ ]:
# Completar aquí
d = np.diag(s)
print(f"Diagonal de S = \n {d}")
D = np.diag(d)
print(f"Matriz con la diagonal de S = \n {D}")
# --------------------


Diagonal de S = 
 [175 223 229 179]
Matriz con la diagonal de S = 
 [[175   0   0   0]
 [  0 223   0   0]
 [  0   0 229   0]
 [  0   0   0 179]]


Calcula la inversa de S, su traza, su determinante, su rango, su norma de Frobenius y su número de condicionamiento

In [ ]:
# Completar aquí
print(f"Inversa de S = \n {np.linalg.inv(s)}")
print(f"Traza de S = {np.trace(s)}")
print(f"Determinante de S = {np.linalg.det(s)}")
print(f"Rango de S = {np.linalg.matrix_rank(s)}")
print(f"Norma de Frobenius de S = {np.linalg.norm(s, 'fro')}")
print(f"Número de condicionamiento de S = {np.linalg.cond(s, 'fro')}")
# --------------------


Inversa de S = 
 [[ 0.50542852 -0.16327184  0.12275813 -0.4341372 ]
 [-0.16327184  0.10890768 -0.07799983  0.11699974]
 [ 0.12275813 -0.07799983  0.06272525 -0.09408788]
 [-0.4341372   0.11699974 -0.09408788  0.39113182]]
Traza de S = 806
Determinante de S = 936719.999999999
Rango de S = 4
Norma de Frobenius de S = 680.5101027905464
Número de condicionamiento de S = 660.4430453104741
