# Práctica 10: Ejercicio para entregar. 
## Autovalores y autovectores en Python


Algunos problemas en Data Science requieren el cálculo de valor propio dominante (el más grande) de una matriz. 

En este ejercicio implementaremos el llamado **Método de la Potencia** para el cálculo de dicho valor propio dominante. Aplicaremos dicho método a una **matriz de Markov** y compararemos los resultados obtenidos con el método **eig** implementado por defecto en Python.



Partimos de una matriz $M$. En este caso, una matriz cuadrada cuyas entradas son positivas y de modo que, para cada columna, si sumamos sus entradas, el resultado es $1$. Este tipo de matrices se llaman de **Markov** y tienen aplicaciones en Álgebra Lineal, Estadística e Informática. Por ejemplo, la siguiente matriz de orden $2$ es de Markov:

$$
M_2 = \left[
    \begin{array}{cc}
    0.2 & 0.4 \\ 
    0.8 & 0.6 \\
    \end{array}
    \right]
$$



Introduce una matriz de Markov de orden $4$, la que tú quieras, y denótala por $M$.

In [1]:
import numpy as np
from numpy.linalg import eig

In [2]:
# Completar aquí
M = np.array([
    [0.2, 0.4, 0.1, 0.5],
    [0.3, 0.4, 0.2, 0.1],
    [0.4, 0.1, 0.5, 0.2],
    [0.1, 0, 0.1, 0.2]
])

print(f"M = \n {M}")
# --------------------


M = 
 [[0.2 0.4 0.1 0.5]
 [0.3 0.4 0.2 0.1]
 [0.4 0.1 0.5 0.2]
 [0.1 0.  0.1 0.2]]


El método de la potencia es un método iterativo donde se parte incialmente de un vector (el llamado **initial guess**). 

Introducimos un vector (1d-array) con cuatro componentes, por ejemplo $v = (0.5, 0.5, 0.5, 0.5)$.

In [3]:
# Completar aquí
v = np.array([0.5, 0.5, 0.5, 0.5])

# --------------------


A continuación vamos a implementar un bucle (loop) con $11$ iteraciones donde en cada iteración vamos a hacer lo siguiente:

1) Multiplicamos $M$ y $v$ y volvemos a denotar por $v$ el resultado, es decir,
**v = M v**.

2) Calculamos la mayor, en valor absoluto, de las componentes de **v**. Recuerda, el valor absoluto de un vector se calcula con **abs** y el máximo aplicando el método **max()**. Denotamos por **lambda** al resultado. Esto nos da una aproximación del valor propio dominante.

3) Dividimos **v** por la mayor de sus componentes. Esto nos da una aproximación del vector propio asociado al valor propio dominante

4) Imprimimos los resultados de 2) y 3) en cada iteración.

In [4]:
# Completar aquí
# 1)
for i in range(11):
    v = M * v
    v_abs = abs(v)
    list_1 = v_abs.tolist()
    Lambda = max(list_1)
    v1 = v / Lambda
    print(f"2) = {Lambda}")
    print(f"3) = {v1}")
# --------------------

2) = [0.2, 0.05, 0.25, 0.1]
3) = [[0.5  4.   0.2  2.5 ]
 [0.75 4.   0.4  0.5 ]
 [1.   1.   1.   1.  ]
 [0.25 0.   0.2  1.  ]]
2) = [0.08000000000000002, 0.005000000000000001, 0.125, 0.020000000000000004]
3) = [[ 0.25   16.      0.04    6.25  ]
 [ 0.5625 16.      0.16    0.25  ]
 [ 1.      1.      1.      1.    ]
 [ 0.0625  0.      0.04    1.    ]]
2) = [0.03200000000000001, 0.0005000000000000001, 0.0625, 0.004000000000000001]
3) = [[1.25000e-01 6.40000e+01 8.00000e-03 1.56250e+01]
 [4.21875e-01 6.40000e+01 6.40000e-02 1.25000e-01]
 [1.00000e+00 1.00000e+00 1.00000e+00 1.00000e+00]
 [1.56250e-02 0.00000e+00 8.00000e-03 1.00000e+00]]
2) = [0.012800000000000004, 5.0000000000000016e-05, 0.03125, 0.0008000000000000003]
3) = [[6.2500000e-02 2.5600000e+02 1.6000000e-03 3.9062500e+01]
 [3.1640625e-01 2.5600000e+02 2.5600000e-02 6.2500000e-02]
 [1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00]
 [3.9062500e-03 0.0000000e+00 1.6000000e-03 1.0000000e+00]]
2) = [0.005120000000000002, 5.0000

Comprueba que, en efecto, se cumple que $M v = \lambda v$, para $\lambda$ el autovalor dominante que acabas de calcular y $v$ su autovector asociado. 

In [5]:
# Completar aquí
# v = M · v
np.allclose(v, Lambda * v1)
# --------------------


True

Comparamos ahora los resultados obtenidos con los que provienen del método **eig** implementado en el submódulo **np.linalg** de Python



In [6]:
# Completar aquí
autovalores, autovectores = eig(M)
print(f"Autovalores = \n {autovalores}")
print(f"Autovectores = \n {autovectores}")
# --------------------

Autovalores = 
 [ 0.93509295 -0.07593169  0.3         0.14083874]
Autovectores = 
 [[ 0.49496716  0.82049304  0.31622777  0.59203256]
 [ 0.55095361 -0.29093726  0.63245553 -0.21102692]
 [ 0.65348979 -0.47598125 -0.63245553 -0.73776023]
 [ 0.15623289 -0.12485401 -0.31622777  0.2463228 ]]


Identificamos el valor propio dominante con valor $\lambda_{max} = 1$. Pero los autovectores, ¿dónde están? ¿dónde está el vector propio asociado a $\lambda_{max}$?

Una pista: investiga la primera columna de la salida anterior.

In [7]:
# Completar aquí
lambda_max = 1
# No hay forma de resolverlo
# --------------------
