# Práctica 4: Ejercicio para entregar. 
## Vectores: aritmética y normas.



Los vectores y matrices de números complejos aparecen frecuentemente en Machine Learning. En concreto, en sistemas de reconocimiento del hablante (speech recognition) y más específicamente en la primera fase, donde se hace uso de una técnica de tratamiento de señales llamada **transformada discreta de Fourier**. En este ejercicio prácticaremos un poco con el tipo de vectores que aparecen en este campo.

Consideremos la llamada **matriz de la transformada de Fourier Discreta** en dimensión 4:
$$
DFT = \frac{1}{2}\left[\begin{array}{cccc}
1 & 1 & 1 & 1\\
1 & e^{2\pi j / 4} & e^{4\pi j / 4} & e^{6\pi j / 4}\\
1 & e^{4\pi j / 4} & e^{6\pi j / 4} & e^{8\pi j / 4}\\
1 & e^{6\pi j / 6} & e^{8\pi j / 8} & e^{10\pi j / 4}
\end{array}
\right]
$$
Nótese que las entradas de esta matriz tienen la forma $e^{2 k n \pi j/N}$, con  $n=0,1,2,3$, $N=4$ y $k = n^T$.

Introduce esta matriz siguiendo los siguiente pasos:

1) Introduce el escalar $N = 4$

2) Genera el vector $n = [0, 1, 2, 3]$ usando el método **arange**

3) Genera el vector $k = n^T$ usando el método **reshape**

4) Genera la matriz $n*k$

5) Genera la matriz con entradas $exp(2j * \pi * k * n / N)$



In [2]:
import numpy as np

In [3]:
# Completar aquí
N = 4
n = np.arange(4)
k = n.reshape(4, 1)
print(f" n = {n}")
print(f" k = \n {k}")
print(f"Matriz n · k \n {n * k}")
DFT = np.exp((2j * np.pi * k * n)/ N)
print(f"DFT = \n {DFT}")
# --------------------


 n = [0 1 2 3]
 k = 
 [[0]
 [1]
 [2]
 [3]]
Matriz n · k 
 [[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]
 [0 3 6 9]]
DFT = 
 [[ 1.0000000e+00+0.0000000e+00j  1.0000000e+00+0.0000000e+00j
   1.0000000e+00+0.0000000e+00j  1.0000000e+00+0.0000000e+00j]
 [ 1.0000000e+00+0.0000000e+00j  6.1232340e-17+1.0000000e+00j
  -1.0000000e+00+1.2246468e-16j -1.8369702e-16-1.0000000e+00j]
 [ 1.0000000e+00+0.0000000e+00j -1.0000000e+00+1.2246468e-16j
   1.0000000e+00-2.4492936e-16j -1.0000000e+00+3.6739404e-16j]
 [ 1.0000000e+00+0.0000000e+00j -1.8369702e-16-1.0000000e+00j
  -1.0000000e+00+3.6739404e-16j  5.5109106e-16+1.0000000e+00j]]


Utiliza la técnica de **slicing** estudiada en la práctica anterior para extraer 
la primer fila (que guardaremos en un vector denotado $v1$) y la tercera columna 
de la matriz $DFT$ (guardada en $v2$)


In [4]:
# Completar aquí
v1 = DFT[:, 1]
v2 = DFT[2, :]
print(f"v1 \n {v1}")
print(f"v2 \n {v2}")
# --------------------


v1 
 [ 1.0000000e+00+0.0000000e+00j  6.1232340e-17+1.0000000e+00j
 -1.0000000e+00+1.2246468e-16j -1.8369702e-16-1.0000000e+00j]
v2 
 [ 1.+0.0000000e+00j -1.+1.2246468e-16j  1.-2.4492936e-16j
 -1.+3.6739404e-16j]


 Calcula:

 1) $v1 + v2$

 2) $v1*v2$, componente a componente

 3) $v1 / v2$, componente a componente

 4) El producto escalar de $v1$ y $v2$

In [5]:
# Completar aquí
print(f"v1 + v2 = \n {v1 + v2}")
print(f"v1 · v2 = \n {v1 * v2}")
print(f"v1 / v2 = \n {v1 / v2}")
print(f"v1.v2 = {v1.dot(v2)}")
# --------------------


v1 + v2 = 
 [ 2.+0.0000000e+00j -1.+1.0000000e+00j  0.-1.2246468e-16j
 -1.-1.0000000e+00j]
v1 · v2 = 
 [ 1.0000000e+00+0.0000000e+00j -1.8369702e-16-1.0000000e+00j
 -1.0000000e+00+3.6739404e-16j  5.5109106e-16+1.0000000e+00j]
v1 / v2 = 
 [ 1.0000000e+00+0.0000000e+00j  6.1232340e-17-1.0000000e+00j
 -1.0000000e+00-1.2246468e-16j -1.8369702e-16+1.0000000e+00j]
v1.v2 = (3.2904645469127765e-16+3.330669073875469e-16j)


Calcula las normas $2$, $1$ y $\infty$ de $v1$

In [7]:
# Completar aquí
l2 = np.linalg.norm(v1, 2)
print(f"Norma 2 de v1 = {l2}")
l1 = np.linalg.norm(v1, 1)
print(f"Norma 1 de v1 = {l1}")
lmax = np.linalg.norm(v1, np.inf)
print(f"Norma infinito de v1 = {lmax}")
# --------------------


Norma 2 de v1 = 2.0
Norma 1 de v1 = 4.0
Norma infinito de v1 = 1.0
