# Práctica 8: Ejercicio para entregar. 
## Factorizaciones LU y Choleski. Aplicación a la resolución de sistemas lineales.



Una clase importante de matrices que aparecen muy frecuentemente en varios campos de la Ingeniería son las llamadas **matrices de Toeplitz**. En dimensión $5$, esta matriz es:
$$
T_5 = \left[\begin{array}{ccccc}
2 & -1 & 0 & 0 & 0\\
-1 & 2 & -1 & 0 & 0\\
0 & -1 & 2 & -1 & 0\\
0 & 0 & -1 & 2 & -1\\
0 & 0 & 0 & -1 & 2
\end{array}
\right]
$$


1) Introduce esta matriz en formato sparse y utilizando el método csr_matrix

2) Tranforma la matriz a formato dense y denota a la matriz resultante con la letra $T$



In [1]:
import numpy as np
from scipy.linalg import lu
from scipy.sparse import csr_matrix

In [9]:
# Completar aquí
# 1)
row = np.array([0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4])
col = np.array([0, 1, 0, 1, 2, 1, 2, 3, 2, 4, 3, 3, 4])
data = np.array([2, -1, -1, 2, -1, -1, 2, -1, -1, -1, 2, -1, 2])

T_mtx = csr_matrix((data, (row, col)), shape=(5, 5))
print(f"Matriz mtx en formato sparse \n {T_mtx}")

# 2)
T = T_mtx.todense()
print(f"Matriz mtx en formato dense \n {T}")
# --------------------


Matriz mtx en formato sparse 
   (0, 0)	2
  (0, 1)	-1
  (1, 0)	-1
  (1, 1)	2
  (1, 2)	-1
  (2, 1)	-1
  (2, 2)	2
  (2, 3)	-1
  (3, 2)	-1
  (3, 3)	2
  (3, 4)	-1
  (4, 3)	-1
  (4, 4)	2
Matriz mtx en formato dense 
 [[ 2 -1  0  0  0]
 [-1  2 -1  0  0]
 [ 0 -1  2 -1  0]
 [ 0  0 -1  2 -1]
 [ 0  0  0 -1  2]]


1) Comprueba, usando un operador booleano, que $T$ es simétrica

2) Comprueba que $T$ es no singular

3) Calcula el número de condicionamiento de $T$


In [4]:
# Completar aquí
# 1)
print(T == T.T)
# Si es una matriz simétrica
print("------------------------------------------------")
# 2)
print(f"Inversa de la matriz T = \n {np.linalg.inv(T)}")
#Tiene matriz inversa, por tanto no es singular
print("------------------------------------------------")
#3)
print(f"Número de condicionamiento de T = \n {np.linalg.cond(T)}")
# --------------------


[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
------------------------------------------------
Inversa de la matriz T = 
 [[0.83333333 0.66666667 0.5        0.33333333 0.16666667]
 [0.66666667 1.33333333 1.         0.66666667 0.33333333]
 [0.5        1.         1.5        1.         0.5       ]
 [0.33333333 0.66666667 1.         1.33333333 0.66666667]
 [0.16666667 0.33333333 0.5        0.66666667 0.83333333]]
------------------------------------------------
Número de condicionamiento de T = 
 13.928203230275486


Calcula la descomposición $PLU$ de $T$ y comprueba que $T = PLU$ 
haciendo uso de un operador booleano. 



In [5]:
# Completar aquí
P, L, U = lu(T)

print(f"P = \n  {P}")
print(f"L = \n {L}")
print(f"U = \n  {U}")

LU = np.dot(L, U)
print(f"LU = \n {LU}")
PLU = np.dot(P, LU)
print(f"PLU = \n {PLU}")

T == PLU
# --------------------


P = 
  [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
L = 
 [[ 1.          0.          0.          0.          0.        ]
 [-0.5         1.          0.          0.          0.        ]
 [ 0.         -0.66666667  1.          0.          0.        ]
 [ 0.          0.         -0.75        1.          0.        ]
 [ 0.          0.          0.         -0.8         1.        ]]
U = 
  [[ 2.         -1.          0.          0.          0.        ]
 [ 0.          1.5        -1.          0.          0.        ]
 [ 0.          0.          1.33333333 -1.          0.        ]
 [ 0.          0.          0.          1.25       -1.        ]
 [ 0.          0.          0.          0.          1.2       ]]
LU = 
 [[ 2. -1.  0.  0.  0.]
 [-1.  2. -1.  0.  0.]
 [ 0. -1.  2. -1.  0.]
 [ 0.  0. -1.  2. -1.]
 [ 0.  0.  0. -1.  2.]]
PLU = 
 [[ 2. -1.  0.  0.  0.]
 [-1.  2. -1.  0.  0.]
 [ 0. -1.  2. -1.  0.]
 [ 0.  0. -1.  2. -1.]
 [ 0.  0.  0. -1.  2.]]


matrix([[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]])

Calcula la factorización de Choleski de $T$

In [6]:
# Completar aquí
from scipy.linalg import ldl

L, D, P = ldl(T)
print(f"L = \n  {L}")
print(f"D = \n {D}")
print(f"P = \n  {P}")

LD = np.dot(L, D)
print(f"LD = \n {LD}")

print(f"LDL^T = \n {np.dot(LD, L.T)}")

# --------------------


L = 
  [[ 1.          0.          0.          0.          0.        ]
 [-0.5         1.          0.          0.          0.        ]
 [ 0.         -0.66666667  1.          0.          0.        ]
 [ 0.          0.         -0.75        1.          0.        ]
 [ 0.          0.          0.         -0.8         1.        ]]
D = 
 [[2.         0.         0.         0.         0.        ]
 [0.         1.5        0.         0.         0.        ]
 [0.         0.         1.33333333 0.         0.        ]
 [0.         0.         0.         1.25       0.        ]
 [0.         0.         0.         0.         1.2       ]]
P = 
  [0 1 2 3 4]
LD = 
 [[ 2.          0.          0.          0.          0.        ]
 [-1.          1.5         0.          0.          0.        ]
 [ 0.         -1.          1.33333333  0.          0.        ]
 [ 0.          0.         -1.          1.25        0.        ]
 [ 0.          0.          0.         -1.          1.2       ]]
LDL^T = 
 [[ 2. -1.  0.  0.  0.]
 [-1.

1) Resuelve el sistema $T^2x = b$, donde $b = \left[ 0, 0, -1, 0, 0\right]^T$

2) Comprueba mediante un operador booleano si $T^2x = b$. Explica a qué se debe el resultado que has obtenido y averigua la forma de resolverlo. Puede resultar útil usar el método np.round()

In [11]:
# Completar aquí
from scipy.linalg import solve
# 1)
TT = T * T
b = np.array([
    [0], 
    [0], 
    [-1], 
    [0], 
    [0]
])
x = solve(TT, b)
print(f"x^T = \n {x}")
x1 = x.T
print(f"x = {x1}")
#2)
print(f"T^2 * x = b: \n {TT.dot(x) == b}")
# El resultado que he obtenido se debe a que hay ciertos errores de redondeo y
# por esa razón sale False en casi todas partes 
print(f"Redondeando: \n {np.round(TT.dot(x)) == b}")
# --------------------


x^T = 
 [[-2.25]
 [-4.  ]
 [-4.75]
 [-4.  ]
 [-2.25]]
x = [[-2.25 -4.   -4.75 -4.   -2.25]]
T^2 * x = b: 
 [[False]
 [False]
 [False]
 [False]
 [ True]]
Redondeando: 
 [[ True]
 [ True]
 [ True]
 [ True]
 [ True]]
