# Práctica 11: Ejercicio para entregar. 
## Factorización SVD y aplicación a PCA (Principal Component Analysis)


En este ejercicio practicaremos el uso de la descomposición en valores singulares (SVD) en el llamado Análisis de Componentes Principales (PCA por sus siglas en inglés). De hecho, PCA es tal importancia en **Data Science**  que el módulo de Python, dedicado al **Machine Learning** tiene implementado el método **pca()** para realizar dicho análisis.



Introduce una matriz **A** de tamaño $5\times 7$ con entradas aleatorias



In [2]:
import numpy as np

In [3]:
# Completar aquí
A = np.random.randn(5, 7)
print(f"A = \n {A}")
# --------------------


A = 
 [[ 1.23863004  1.13036074  0.77791546 -0.40285599 -0.26182464  1.2234603
   0.23830111]
 [-1.08004111 -1.46921466  1.6881494   0.6622768   0.27364674  0.31449394
  -1.36098222]
 [-0.78898415 -0.75349715  0.26477929 -0.40908658  0.20381173 -1.05459886
   0.55535651]
 [ 0.19950072 -0.04633745  0.02862858  1.38638292 -1.06857968  0.53422688
  -2.63473605]
 [ 1.03617141 -1.29986596 -0.7013159  -0.58330851  2.01386672  0.28184532
  -0.65837888]]


Calcula la media de las entradas de cada columna en la matriz $A^T$. Esto se hace con el método **mean()** de **numpy**. Lo puedes ver en [numpy.mean() API](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.mean.html)

In [4]:
# Completar aquí
M = np.mean(A, axis=0)
print(M)
# --------------------


[ 0.12105538 -0.48771089  0.41163137  0.13068173  0.23218417  0.25988551
 -0.77208791]


Mediante una operación tipo **broadcasting** calcula $C = A - M$

In [5]:
# Completar aquí
C = A - M
print(f"C = \n {C}")
# --------------------


C = 
 [[ 1.11757466  1.61807164  0.3662841  -0.53353771 -0.49400881  0.96357478
   1.01038902]
 [-1.20109649 -0.98150376  1.27651803  0.53159507  0.04146256  0.05460842
  -0.58889431]
 [-0.91003953 -0.26578625 -0.14685208 -0.53976831 -0.02837244 -1.31448438
   1.32744442]
 [ 0.07844533  0.44137344 -0.38300278  1.25570119 -1.30076386  0.27434137
  -1.86264815]
 [ 0.91511603 -0.81215506 -1.11294727 -0.71399023  1.78168255  0.0219598
   0.11370903]]


En Estadística, dada una matriz de datos $C$, se introduce el concepto de **matriz de covarianza** (lo veréis en las asignaturas de Estadística), que trata de medir la correlación de los datos contenidos en columnas distintas. En Python se calcula escribiendo **D = np.cov(C.T)**. Puedes verlo en [numpy.cov() API](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.cov.html)

Calcula la matriz de covarianza de la matriz $C$ anterior. Verás que te sale una matriz simétrica.

In [6]:
# Completar aquí
D = np.cov(C.T)
print(f"D = \n {D}")
# --------------------


D = 
 [[ 1.09084222  0.63012004 -0.50968774 -0.32460868  0.23808379  0.56228152
   0.14660452]
 [ 0.63012004  1.12663854  0.0284091  -0.02687447 -0.71340536  0.48953969
   0.23639863]
 [-0.50968774  0.0284091   0.79264265  0.21903171 -0.40214396  0.12154298
   0.00256613]
 [-0.32460868 -0.02687447  0.21903171  0.73629329 -0.65113662  0.1383137
  -0.99719075]
 [ 0.23808379 -0.71340536 -0.40214396 -0.65113662  1.27823704 -0.18854576
   0.51605945]
 [ 0.56228152  0.48953969  0.12154298  0.1383137  -0.18854576  0.68376826
  -0.32799564]
 [ 0.14660452  0.23639863  0.00256613 -0.99719075  0.51605945 -0.32799564
   1.65304475]]


Calcula la factorización **SVD** de la matriz $D$ anterior.



In [7]:
# Completar aquí
from scipy.linalg import svd
U, s, V = svd(D)
print(f"U = \n {U}")
print(f"s = {s}")
print(f"V = \n {V}")
# --------------------


U = 
 [[-0.1771092   0.57100415  0.4099557   0.05278418  0.58638893  0.31712798
   0.16527134]
 [ 0.09682082  0.65530044 -0.26418732 -0.1634272  -0.59138691  0.19007512
   0.28077864]
 [ 0.19753955 -0.10040897 -0.48026909  0.69786233  0.15397773  0.43149631
   0.15273415]
 [ 0.48905757 -0.09274477  0.08433994 -0.05704323  0.18444075 -0.38918324
   0.74590346]
 [-0.51682439 -0.23949876  0.42944665  0.36083905 -0.41514579  0.07182959
   0.42825008]
 [ 0.15138786  0.39005727  0.18504874  0.59131636 -0.11815521 -0.58051456
  -0.30013524]
 [-0.62532644  0.12785818 -0.55290351 -0.01948747  0.24975052 -0.42835965
   0.20166746]]
s = [2.94296325e+00 2.27340232e+00 1.52058545e+00 6.24515727e-01
 2.95739231e-16 1.99152407e-16 2.19369200e-18]
V = 
 [[-0.1771092   0.09682082  0.19753955  0.48905757 -0.51682439  0.15138786
  -0.62532644]
 [ 0.57100415  0.65530044 -0.10040897 -0.09274477 -0.23949876  0.39005727
   0.12785818]
 [ 0.4099557  -0.26418732 -0.48026909  0.08433994  0.42944665  0.18504874


A partir de los valores singulares, construye la matriz **Sigma** de la descomposición **SVD**

In [8]:
# Completar aquí
Sigma = np.zeros((D.shape[0], D.shape[1]))
Sigma[:D.shape[0], :D.shape[0]] = np.diag(s)
print(f"Sigma = \n {Sigma}")
# --------------------


Sigma = 
 [[2.94296325e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.27340232e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.52058545e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 6.24515727e-01
  0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  2.95739231e-16 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 1.99152407e-16 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 2.19369200e-18]]


Extrae la información de los datos originales asociados a los $4$ primeros valores singulares

In [10]:
# Completar aquí
n_componentes = 4
Sigma = Sigma[:, :n_componentes]
print(f"Sigma reducida = \n {Sigma}")

T = U.dot(Sigma)
print(f"T = \n {T}") 
# T reemplaza a la matriz original D pues contiene la escala de los datos de D.
# --------------------


Sigma reducida = 
 [[2.94296325 0.         0.         0.        ]
 [0.         2.27340232 0.         0.        ]
 [0.         0.         1.52058545 0.        ]
 [0.         0.         0.         0.62451573]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]]
T = 
 [[-0.52122586  1.29812216  0.62337267  0.03296455]
 [ 0.28494011  1.48976153 -0.4017194  -0.10206286]
 [ 0.58135164 -0.22826999 -0.73029019  0.435826  ]
 [ 1.43927845 -0.21084617  0.12824609 -0.03562439]
 [-1.52099518 -0.54447704  0.65301033  0.22534966]
 [ 0.44552892  0.88675711  0.28138242  0.36928637]
 [-1.84031272  0.29067309 -0.84073703 -0.01217023]]


Todo este proceso que hemos realizado desde el principio y paso a paso (from scratch, que dicen en inglés) está integrado en el módulo **scikit-learn** de Python. En concreto, en el método **pca**.
Quizás será así como lo usaréis en las asignaturas de **Machine Learning**.
Más información en [sklearn.decomposition.PCA API](http://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCAhtml)