# Práctica 3: Ejercicio para entregar. 
## NumPy arrays: index, slice, reshape, broadcasting, etc.



Introduce tu DNI en la forma de 1d-array.

A continuación, selecciona e imprime la siguiente información de dicho array:

1) el primer elemento
2) el último
3) El que ocupa la segunda posición (empezando desde la izquierda)
4) el que ocupa la antepenúltima 
5) los tres primeros elementos
6) los 4 últimos elementos

In [1]:
import numpy as np

In [2]:
# Completar aquí
dni = np.array([2, 6, 6, 4, 9, 1, 1, 0])
print(dni[0])
print(dni[-1])
print(dni[1])
print(dni[-2])
print(dni[0:3])
print(dni[4:])
# --------------------


2
0
6
1
[2 6 6]
[9 1 1 0]


Cambia la forma del 1d-array que contiene tu nombre para convertirlo en un 2d-array (matriz) de tamaño $2\times 4$, es decir dos filas y cuatro columnas. 

A continuación, selecciona e imprime los siguientes datos del nuevo 2d-array:

1) la primera fila
2) la segunda columna

In [3]:
# Completar aquí
dni = np.array([
    [2, 6],
    [6, 4],
    [9, 1],
    [1, 0]
])
x, y = dni[0, :], dni[:, 1]
print(f"primera fila = \n {x}")
print(f"segunda columna = \n {y}")
# --------------------


primera fila = 
 [2 6]
segunda columna = 
 [6 4 1 0]


Imaginemos que el 2d-array del ejercicio anterior contiene las features $X$ y las labels $y$ de un modelo de Machine Learning. En concreto, $X$ almacena todos los datos excepto la última columna mientras que $y$ contiene los datos de la última columna.

Genera $X$ e $y$.

In [4]:
# Completar aquí
x, y = dni[:, :-1], dni[:, -1]
print(f"features X = \n {x}")
print(f"labels y = {y}")
# --------------------


features X = 
 [[2]
 [6]
 [9]
 [1]]
labels y = [6 4 1 0]


Supongamos ahora que queremos separar los datos del 2d-array en dos subconjuntos, un training dataset y un test dataset.

Training dataset será la primera fila y  test dataset será la segunda fila

In [5]:
# Completar aquí
split = 0
train, test = dni[split, :], dni[split + 1, :]
print(f"training dataset = {train}")
print(f"test dataset = {test}")
# --------------------


training dataset = [2 6]
test dataset = [6 4]


Introduce un escalar que se corresponda con tu nota de entrada al grado de Ciencia e Ingeniería de Datos. A continuación realiza las siguientes operaciones:

1) Suma el escalar al 2d-array anterior
2) Multiplica el escalar al 2d-array anterior
3) Divide el 2d-array por el escalar

In [6]:
# Completar aquí
nota = 11
x = nota + dni
print(f"Suma = \n {x}")
y = dni * nota
print(f"Multiplicación = \n {y}")
z = dni / nota
print(f"División = \n {z}")
# --------------------


Suma = 
 [[13 17]
 [17 15]
 [20 12]
 [12 11]]
Multiplicación = 
 [[22 66]
 [66 44]
 [99 11]
 [11  0]]
División = 
 [[0.18181818 0.54545455]
 [0.54545455 0.36363636]
 [0.81818182 0.09090909]
 [0.09090909 0.        ]]
