# Práctica 2: Ejercicio para entregar 

## Introducción a N-dimensional arrays en Python


Partimos de tu número de DNI, que debe contener 9 dígitos.
DNI = abcdefgh  . Por ejemplo, DNI = 23982606

Introduce tu DNI en forma de 1d-array e imprimelo junto con sus atributos forma, tamaño y tipo

In [1]:
# Completar aquí
import numpy as np
DNI = 26649110
x = np.array([26649110])
print(x)
print(type(x))
print(x.shape)
print(x.size)
print(x.dtype)
# --------------------


[26649110]
<class 'numpy.ndarray'>
(1,)
1
int32


Define e imprimer los siguientes ndarrays:

1) Una matriz cuadrada de unos y de tamaño el dígito más grande de tu DNI.

2) Una matriz de tamaño $m\times n$, donde $m$ es el dígito más pequeño (excluido el $0$) de tu DNI, y $n$ el dígito más grande, cuyas entradas sean todo cero.

3) Un vector cuyo primer elemento sea el dígito más pequeño de tu DNI, cuyo último elemento sea el dígito más grande, y que contenga $5$ elementos equiespaciados.

4) Un vector cuyo primer elemento sea el dígito más pequeño de tu DNI, el último el dígito más grande y donde cada elemento del array esté separado del siguiente en una unidad. 

In [2]:
# Completar aquí
a = np.ones([9, 9])
print(f"Apartado 1:  \n {a}")
b = np.zeros([1, 9])
print(f"Apartado 2:  \n {b}")
c = np.linspace(1, 9, 5)
print(f"Apartado 3: \n {c}")
d = np.arange(1, 9, 1)
print(f"Apartado 4: \n {d}")
# --------------------


Apartado 1:  
 [[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Apartado 2:  
 [[0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Apartado 3: 
 [1. 3. 5. 7. 9.]
Apartado 4: 
 [1 2 3 4 5 6 7 8]


Apila de manera horizontal los vectores introducidos en los apartados 3) y 4) del apartado anterior.

Calcula el tamaño el array resultante.

In [9]:
# Completar aquí
x = np.hstack((c, d))
print(x)
print(x.size)
# --------------------


[1. 3. 5. 7. 9. 1. 2. 3. 4. 5. 6. 7. 8.]
13



Utiliza **vstack** para generar una matriz con dos filas, cada una de las cuales contenga al vector gnerado en el apartado 4) anterior.

Calcula el tipo o forma (shape) del array generado.

In [10]:
# Completar aquí
x1 = np.array((d, d))
print(x1)
print(x1.shape)
# --------------------


[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]
(2, 8)


Intenta apilar, también de manera vertical, los vectores de los apartados 3) y 4) anteriores. 

Obtienes un error. ¿A qué se debe este error?

In [ ]:
# Completar aquí
x2 = np.array(c)
v1 = np.vstack((x2,x1))
print(v1)
#Al ejecutar el codigo da error debido a que las dimensiones no coinciden.
# --------------------


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 8

Introduce tu DNI en formato lista y tupla. Convierte ambos a formato **ndarray** 

In [ ]:
# Completar aquí
lista = [2, 6, 6, 4, 9, 1, 1, 0]
lista = np.array(lista)
tupla = (2, 6, 6, 4, 9, 1, 1, 0)
tupla = np.array(tupla)
print(f"lista: \n {lista}")
print(f"tupla: \n {tupla}")
# --------------------


lista: 
 [2 6 6 4 9 1 1 0]
tupla: 
 [2 6 6 4 9 1 1 0]
