# Práctica 2: Ejercicio para entregar 

## Introducción a N-dimensional arrays en Python


Partimos de tu número de DNI, que debe contener 9 dígitos.
DNI = abcdefgh  . Por ejemplo, DNI = 23982606

Introduce tu DNI en forma de 1d-array e imprimelo junto con sus atributos forma, tamaño y tipo

In [11]:
import numpy as np

In [12]:
# Completar aquí
dni = np.array([2,6,6,4,9,1,1,0])
print(dni)
print(dni.shape)
print(dni.size)
print(type(dni))
# --------------------


[2 6 6 4 9 1 1 0]
(8,)
8
<class 'numpy.ndarray'>


Define e imprimer los siguientes ndarrays:

1) Una matriz cuadrada de unos y de tamaño el dígito más grande de tu DNI.

2) Una matriz de tamaño $m\times n$, donde $m$ es el dígito más pequeño (excluido el $0$) de tu DNI, y $n$ el dígito más grande, cuyas entradas sean todo cero.

3) Un vector cuyo primer elemento sea el dígito más pequeño de tu DNI, cuyo último elemento sea el dígito más grande, y que contenga $5$ elementos equiespaciados.

4) Un vector cuyo primer elemento sea el dígito más pequeño de tu DNI, el último el dígito más grande y donde cada elemento del array esté separado del siguiente en una unidad. 

In [13]:
# Completar aquí
# Apartado 1
print(np.ones([9, 9]))

print()

# Apartado 2
print(np.zeros([1,9]))

print()

# Apartado 3
print(np.linspace(1, 9, 5))

print()

# Apartado 4
print(np.arange(1,9))
# --------------------


[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]]

[1. 3. 5. 7. 9.]

[1 2 3 4 5 6 7 8]


Apila de manera horizontal los vectores introducidos en los apartados 3) y 4) del apartado anterior.

Calcula el tamaño el array resultante.

In [14]:
# Completar aquí
x = np.hstack((np.linspace(1, 9, 5), np.arange(1,9)))

print(x)
print(type(x))
# --------------------


[1. 3. 5. 7. 9. 1. 2. 3. 4. 5. 6. 7. 8.]
<class 'numpy.ndarray'>



Utiliza **vstack** para generar una matriz con dos filas, cada una de las cuales contenga al vector gnerado en el apartado 4) anterior.

Calcula el tipo o forma (shape) del array generado.

In [15]:
# Completar aquí
matriz_h = np.vstack((np.arange(1,9), np.arange(1,9)))

print(matriz_h)
# --------------------


[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


Intenta apilar, también de manera vertical, los vectores de los apartados 3) y 4) anteriores. 

Obtienes un error. ¿A qué se debe este error?

In [16]:
# Completar aquí
np.vstack((np.linspace(1, 9, 5), np.arange(1,9)))

# No se pueden apilar debido a que tienen un tamaño distinto
# --------------------


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 8

Introduce tu DNI en formato lista y tupla. Convierte ambos a formato **ndarray** 

In [17]:
# Completar aquí
dni_lista = [2,6,6,4,9,1,1,0]
dni_tupla = (2,6,6,4,9,1,1,0)

print(np.array(dni_lista))
print(type(np.array(dni_lista)))
print(np.array(dni_tupla))
print(type(np.array(dni_tupla)))
# --------------------


[2 6 6 4 9 1 1 0]
<class 'numpy.ndarray'>
[2 6 6 4 9 1 1 0]
<class 'numpy.ndarray'>
