# Práctica 7: Ejercicio para entregar. 
## Tensores en Ciencia de Datos.



In [1]:
import numpy as np

El fichero la_manga.jpg contiene dos fotos de La Manga del Mar Menor, una de los años 60 y otra actual. 

![imagen de La Manga del Mar Menor en los años 60 y en la actualidad](../data/la_manga.jpg)

Carga dicho fichero y convierte la imagen en un tensor. A continuación, imprime por pantalla el tensor asociado a la imagen y guárdalo en la carpeta data con el nombre **tensor_la_manga.npy**



In [2]:
# Completar aquí
from PIL import Image

tensor_la_manga = Image.open('../data/la_manga.jpg')
la_manga_array = np.array(tensor_la_manga)
print(f"Foto de La Manga como array = \n {la_manga_array}")
np.save('../data/tensor_la_manga.npy', la_manga_array)
# --------------------


Foto de La Manga como array = 
 [[[192 192 192]
  [190 190 190]
  [189 189 189]
  ...
  [149 176 195]
  [149 176 195]
  [149 176 195]]

 [[193 193 193]
  [191 191 191]
  [189 189 189]
  ...
  [148 175 194]
  [148 175 194]
  [148 175 194]]

 [[194 194 194]
  [192 192 192]
  [190 190 190]
  ...
  [146 173 192]
  [146 173 192]
  [146 173 192]]

 ...

 [[184 184 184]
  [143 143 143]
  [121 121 121]
  ...
  [ 59  89  81]
  [ 63  90  83]
  [ 61  91  83]]

 [[174 174 174]
  [133 133 133]
  [119 119 119]
  ...
  [ 63  94  86]
  [ 66  96  88]
  [ 66  97  89]]

 [[160 160 160]
  [123 123 123]
  [117 117 117]
  ...
  [ 67  98  90]
  [ 70 101  93]
  [ 70 101  93]]]


Calcula la forma y dimensión del tensor generado. 

In [3]:
# Completar aquí
print(f'Forma del tensor: {la_manga_array.shape}')
print(f'Dimensión del tensor: {la_manga_array.ndim}')
# --------------------


Forma del tensor: (720, 960, 3)
Dimensión del tensor: 3


Utiliza la técnica de **slicing** que vimos en la práctica 3 para generar dos vectores. Uno de ellos, denotado **v1** se ha de corresponder con la primera fila del tensor que ves por pantalla; el segundo vector, **v2**, está formado por la segunda fila que ves por pantalla.  

In [4]:
# Completar aquí
v1 = la_manga_array[0, 0]
v2 = la_manga_array[0, 1]
print(f"v1 = {v1}")
print(f"v2 = {v2}")
# --------------------


v1 = [192 192 192]
v2 = [190 190 190]


Calcula:

1) el producto tensorial de **v1** y **v2**

2) el producto de Hadamard de **v1** y **v2**

3) el producto escalar de **v1** y **v2**

In [5]:
# Completar aquí
print(f"v1 ⊗ v2 = \n {np.tensordot(v1, v2, axes=0)}")
print(f'v1 * v2 = {v1 * v2}')
print(f"Producto escalar de v1 y v2 = {np.tensordot(v1, v2, axes=1)}")
# --------------------


v1 ⊗ v2 = 
 [[128 128 128]
 [128 128 128]
 [128 128 128]]
v1 * v2 = [128 128 128]
Producto escalar de v1 y v2 = 128


Introduce manualmente, usando **np.array()**, los vectores **v1** y **v2** anteriores y denótaos por **z1** y **z2**, respectivamente.

A contrinuación realiza los mismos cálculos (producto tensorial, producto de Hadamard y producto escalar) con los vectores **z1** y **z2**.

In [6]:
# Completar aquí
z1 = np.array([192, 192, 192])
z2 = np.array([190, 190, 190])
print(f"z1 ⊗ z2 = \n {np.tensordot(z1, z2, axes=0)}")
print(f'z1 * z2 = {z1 * z2}')
print(f"Producto escalar de z1 y z2 = {np.tensordot(z1, z2, axes=1)}")
# --------------------


z1 ⊗ z2 = 
 [[36480 36480 36480]
 [36480 36480 36480]
 [36480 36480 36480]]
z1 * z2 = [36480 36480 36480]
Producto escalar de z1 y z2 = 109440


Como puedes ver, obtienes resultados distintos. 

Busca una explicación convincente para esta discrepancia de resultados.
Te puede resultar útil estudiar los atributos **shape**, **type** y **dtype** de los vectores **v1**, **v2**, **z1** y **z2**.

Investiga y dí todo lo que sepas sobre este asunto.

In [7]:
# Completar aquí
print("Atributos de v1")
print(f"Shape = {v1.shape}")
print(f"Dtype = {v1.dtype}")
print(f"Type = {type(v1)}")
print()
print("Atributos de v2")
print(f"Shape = {v2.shape}")
print(f"Dtype = {v2.dtype}")
print(f"Type = {type(v2)}")
print()
print("Atributos de z1")
print(f"Shape = {z1.shape}")
print(f"Dtype = {z1.dtype}")
print(f"Type = {type(z1)}")
print()
print("Atributos de z2")
print(f"Shape = {z2.shape}")
print(f"Dtype = {z2.dtype}")
print(f"Type = {type(z2)}")

# Observando los distintos atributos he llegado a la conclusión de que estos
# vectores tienen el mismo tamaño y son de la misma clase (numpy.ndarray). Sin 
# embargo, hay diferencia en los resultados debido a que v1 y v2 están 
# diseñados con enteros sin signo de 8 bits mientras que z1 y z2 están diseñados 
# con enteros con signo de 32 bits, eso hace que al manipularlos den resultados
# difentes. 
# --------------------


Atributos de v1
Shape = (3,)
Dtype = uint8
Type = <class 'numpy.ndarray'>

Atributos de v2
Shape = (3,)
Dtype = uint8
Type = <class 'numpy.ndarray'>

Atributos de z1
Shape = (3,)
Dtype = int32
Type = <class 'numpy.ndarray'>

Atributos de z2
Shape = (3,)
Dtype = int32
Type = <class 'numpy.ndarray'>
