# Práctica 5: Ejercicio para entregar.
## Dot Product Similarity Matrix

Una clase de matrices que aparencen de manera recurrente en varias aplicaciones
de Machine Learning son matrices S que toman la forma S = DD^T, donde D es una
matriz de datos de tamaño nxd y D^T es su traspuesta.
En este ejercicio practicaremos el manejo de este tipo de matrices haciendo uso
del módulo Numpy de Python.

Introduce una matriz D de 4 filas y 8 columnas de modo que la primera fila
contenga tu número de DNI y el resto de filas números de DNI de algunos
familiares tuyos.
Imprime también por pantalla la matriz D

In [ ]:
import numpy as np

In [ ]:
# Completar aquí
D = np.array([
    [2,6,6,4,9,1,1,0],
    [3,6,4,7,9,5,1,0],
    [4,5,3,8,8,1,2,6],
    [7,6,4,1,1,9,4,1]
])
print(f"D =\n{D}")
# --------------------


D =
[[2 6 6 4 9 1 1 0]
 [3 6 4 7 9 5 1 0]
 [4 5 3 8 8 1 2 6]
 [7 6 4 1 1 9 4 1]]


Calcula, usando las dos formas estudiadas en clase, e imprime por pantalla
la matriz S = DD^T

In [ ]:
# Completar aquí
S = D.dot(D.T)
print(f"S = \n {S}")
# --------------------


S = 
 [[175 181 163 100]
 [181 217 189 138]
 [163 189 219 109]
 [100 138 109 201]]


Introduce un vector b no nulo de dimensión 4, el que quieras, y calcula, de las
dos formas que vimos en clase, el producto de S y b, es decir, S*b.
Calcula también b*S. Compara los resultados de S*b y b*S.
¿Qué explicación encuentras de ambos resultados?

In [ ]:
# Completar aquí
b = np.array([1,4,5,3])
print(f"Sb = \n {S * b}")
print(f"bS = \n {b * S}")
# Los resultados son los mismos debido a la propiedad distributiva donde S*b=b*S
# --------------------


Sb = 
 [[ 175  724  815  300]
 [ 181  868  945  414]
 [ 163  756 1095  327]
 [ 100  552  545  603]]
bS = 
 [[ 175  724  815  300]
 [ 181  868  945  414]
 [ 163  756 1095  327]
 [ 100  552  545  603]]


Introduce un escalar a, número real, y calcula a*S

In [ ]:
# Completar aquí
a = 10
print(f"a*S = \n{a*S}")
# --------------------


a*S = 
[[1750 1810 1630 1000]
 [1810 2170 1890 1380]
 [1630 1890 2190 1090]
 [1000 1380 1090 2010]]


Calcula el producto de Hadamard de S y S.
Calcula, componente a componente de S dividido por S.

In [ ]:
# Completar aquí
print(f"S*S = \n{S*S}")
print(f"S/S = \n{S/S}")
# --------------------


S*S = 
[[30625 32761 26569 10000]
 [32761 47089 35721 19044]
 [26569 35721 47961 11881]
 [10000 19044 11881 40401]]
S/S = 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Comprueba que S es simétrica utilizando un operador Booleano

In [ ]:
# Completar aquí
print(f"¿S es simétrica? \n{S == S.T}")
# --------------------


¿S es simétrica? 
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


Calcula las partes triangular inferior y superior de D.


In [ ]:

# Completar aquí
print(f"Triangular inferior de D = \n{np.tril(D)}")
print(f"Triangular superior de D = \n{np.triu(D)}")
# --------------------


Triangular inferior de D = 
[[2 0 0 0 0 0 0 0]
 [3 6 0 0 0 0 0 0]
 [4 5 3 0 0 0 0 0]
 [7 6 4 1 0 0 0 0]]
Triangular superior de D = 
[[2 6 6 4 9 1 1 0]
 [0 6 4 7 9 5 1 0]
 [0 0 3 8 8 1 2 6]
 [0 0 0 1 1 9 4 1]]


Extrae la diagonal de S y genera una matriz diagonal con la diagonal de S

In [ ]:
# Completar aquí
d = np.diag(S)
x = np.diag(d)
print(d)
print(x)
# --------------------


[175 217 219 201]
[[175   0   0   0]
 [  0 217   0   0]
 [  0   0 219   0]
 [  0   0   0 201]]


Calcula la inversa de S, su traza, su determinante, su rango, su norma de Frobenius y su número de condicionamiento

In [ ]:
# Completar aquí
print(f"Inversa de S = \n {np.linalg.inv(S)}")
print(f"Traza de S = {np.trace(S)}")
print(f"Determinante de S = {np.linalg.det(S)}")
print(f"Rango de S = {np.linalg.matrix_rank(S)}")
print(f"Norma de Frobenius de S = {np.linalg.norm(S, 'fro')}")
print(f"Número de condicionamiento de S = {np.linalg.cond(S, 'fro') * np.linalg.norm(np.linalg.inv(S), 'fro')}")
# --------------------


Inversa de S = 
 [[ 0.04601371 -0.03916935 -0.00333495  0.0058085 ]
 [-0.03916935  0.05788966 -0.01468774 -0.01229291]
 [-0.00333495 -0.01468774  0.01901025  0.00143425]
 [ 0.0058085  -0.01229291  0.00143425  0.00974745]]
Traza de S = 812
Determinante de S = 28453801.999999978
Rango de S = 4
Norma de Frobenius de S = 661.8368378988888
Número de condicionamiento de S = 6.499819743637441
