# Práctica 4: Ejercicio para entregar. 
## Vectores: aritmética y normas.



Los vectores y matrices de números complejos aparecen frecuentemente en Machine Learning. En concreto, en sistemas de reconocimiento del hablante (speech recognition) y más específicamente en la primera fase, donde se hace uso de una técnica de tratamiento de señales llamada **transformada discreta de Fourier**. En este ejercicio prácticaremos un poco con el tipo de vectores que aparecen en este campo.

Consideremos la llamada **matriz de la transformada de Fourier Discreta** en dimensión 4:
$$
DFT = \frac{1}{2}\left[\begin{array}{cccc}
1 & 1 & 1 & 1\\
1 & e^{2\pi j / 4} & e^{4\pi j / 4} & e^{6\pi j / 4}\\
1 & e^{4\pi j / 4} & e^{6\pi j / 4} & e^{8\pi j / 4}\\
1 & e^{6\pi j / 6} & e^{8\pi j / 8} & e^{10\pi j / 4}
\end{array}
\right]
$$
Nótese que las entradas de esta matriz tienen la forma $e^{2 k n \pi j/N}$, con  $n=0,1,2,3$, $N=4$ y $k = n^T$.

Introduce esta matriz siguiendo los siguiente pasos:

1) Introduce el escalar $N = 4$

2) Genera el vector $n = [0, 1, 2, 3]$ usando el método **arange**

3) Genera el vector $k = n^T$ usando el método **reshape**

4) Genera la matriz $n*k$

5) Genera la matriz con entradas $exp(2j * \pi * k * n / N)$



In [79]:
import numpy as np

In [80]:
dft = 0.5*np.array([
    [1, 1, 1, 1],
    [1, np.exp((2j*np.pi)/4), np.exp((4j*np.pi)/4), np.exp((6j*np.pi)/4)],
    [1, np.exp((4j*np.pi)/4), np.exp((6j*np.pi)/4), np.exp((8j*np.pi)/4)],
    [1, np.exp((6j*np.pi)/4), np.exp((8j*np.pi)/4), np.exp((10j*np.pi)/4)]
])

In [81]:
# Completar aquí
N = 4

n = np.arange(4)
print(f"n = {n}")
print()
k = n.reshape((n.shape[0], 1))
print(f"k = \n{k}")
print()
print(f"n * k = \n{n * k}")
print()
x = np.exp(2j*np.pi*k*n/N)
print(f"x = \n{x}")
# --------------------


n = [0 1 2 3]

k = 
[[0]
 [1]
 [2]
 [3]]

n * k = 
[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]
 [0 3 6 9]]

x = 
[[ 1.0000000e+00+0.0000000e+00j  1.0000000e+00+0.0000000e+00j
   1.0000000e+00+0.0000000e+00j  1.0000000e+00+0.0000000e+00j]
 [ 1.0000000e+00+0.0000000e+00j  6.1232340e-17+1.0000000e+00j
  -1.0000000e+00+1.2246468e-16j -1.8369702e-16-1.0000000e+00j]
 [ 1.0000000e+00+0.0000000e+00j -1.0000000e+00+1.2246468e-16j
   1.0000000e+00-2.4492936e-16j -1.0000000e+00+3.6739404e-16j]
 [ 1.0000000e+00+0.0000000e+00j -1.8369702e-16-1.0000000e+00j
  -1.0000000e+00+3.6739404e-16j  5.5109106e-16+1.0000000e+00j]]


Utiliza la técnica de **slicing** estudiada en la práctica anterior para extraer la primer fila (que guardaremos en un vector denotado $v1$) y la tercera columna de la matriz $DFT$ (guardada en $v2$)


In [82]:
# Completar aquí
v1 = dft[:1]

v2 = dft[2:]

print(f"v1 = \n{v1}")
print(f"v2 = \n{v2}")
# --------------------


v1 = 
[[0.5+0.j 0.5+0.j 0.5+0.j 0.5+0.j]]
v2 = 
[[ 5.00000000e-01+0.0000000e+00j -5.00000000e-01+6.1232340e-17j
  -9.18485099e-17-5.0000000e-01j  5.00000000e-01-1.2246468e-16j]
 [ 5.00000000e-01+0.0000000e+00j -9.18485099e-17-5.0000000e-01j
   5.00000000e-01-1.2246468e-16j  1.53080850e-16+5.0000000e-01j]]


 Calcula:

 1) $v1 + v2$

 2) $v1*v2$, componente a componente

 3) $v1 / v2$, componente a componente

 4) El producto escalar de $v1$ y $v2$

In [83]:
# Completar aquí
print(f"v1 + v2 = \n {v1 + v2}")
print(f"v1 * v2 = \n {v1 * v2}")
print(f"v1 / v2 = \n {v1 / v2}")
print(f"v1.v2 = \n {v1.dot(v2.T)}")

# He calculado el producto escalar usando la traspuesta de v2 debido a que no se
# pueden calcular de forma convencional ya que v1 tiene forma (1,4) y v2 forma 
# (2, 4), al usar la traspuesta queda resuelto
# --------------------


v1 + v2 = 
 [[1. +0.0000000e+00j 0. +6.1232340e-17j 0.5-5.0000000e-01j
  1. -1.2246468e-16j]
 [1. +0.0000000e+00j 0.5-5.0000000e-01j 1. -1.2246468e-16j
  0.5+5.0000000e-01j]]
v1 * v2 = 
 [[ 2.50000000e-01+0.000000e+00j -2.50000000e-01+3.061617e-17j
  -4.59242550e-17-2.500000e-01j  2.50000000e-01-6.123234e-17j]
 [ 2.50000000e-01+0.000000e+00j -4.59242550e-17-2.500000e-01j
   2.50000000e-01-6.123234e-17j  7.65404249e-17+2.500000e-01j]]
v1 / v2 = 
 [[ 1.0000000e+00+0.0000000e+00j -1.0000000e+00-1.2246468e-16j
  -1.8369702e-16+1.0000000e+00j  1.0000000e+00+2.4492936e-16j]
 [ 1.0000000e+00+0.0000000e+00j -1.8369702e-16+1.0000000e+00j
   1.0000000e+00+2.4492936e-16j  3.0616170e-16-1.0000000e+00j]]
v1.v2 = 
 [[0.25-2.500000e-01j 0.5 -6.123234e-17j]]


Calcula las normas $2$, $1$ y $\infty$ de $v1$

In [84]:
# Completar aquí
print(f"Norma 1 de v1 = {np.linalg.norm(v1, 1)}")
print(f"Norma 2 de v1 = {np.linalg.norm(v1, 2)}")
print(f"Norma oo de v1 = {np.linalg.norm(v1, np.inf)}")
# --------------------


Norma 1 de v1 = 0.5
Norma 2 de v1 = 1.0
Norma oo de v1 = 2.0
