# Examen de prácticas. Curso 22-23. Convocatoria Mayo 2023

## Pseudo-inversa de Moore-Penrose de una matriz y aplicación a sistemas lineales 

Algunos problemas de **Machine Learning**, por ejemplo la aproximación por mínimos cuadrados, conducen a la resolución de sistemas lineales del tipo
$$
Ax = b
$$
que no tienen solución. 

En este ejercicio veremos cómo la Descomposición en Valores Singulares (SVD) ayuda a paliar esta situación y a encontrar un vector $x_{-}$ que minimiza la distancia entre $Ax$ y $b$, y por tanto, en algún sentido, reemplaza esa solución que no existe.


Introduce la matriz $A$ y el vector $b$ siguientes. Asegúrate de que el tipo de datos en la matriz y el vector es **float64**.

$$
A=\begin{bmatrix}
1&1&1\\
-1&0&1\\
1&0&1\\
1&1&1
\end{bmatrix},
\qquad 
b = \begin{bmatrix}
1\\
1\\
1\\
-1
\end{bmatrix}.
$$
Imprime ambos por pantalla. También el tipo de datos.

**Puntos = 0.5**



In [3]:
import numpy as np
from scipy.linalg import svd

In [4]:
# Completar aquí
A = np.array([
    [1,1,1],
    [-1,0,1],
    [1,0,1],
    [1,1,1]
], dtype=np.float64)

b = np.array([1,1,1,-1], dtype=np.float64)

print(f"A = \n {A}")
print(f"dtype de A = {A.dtype}")
print(f"b = {b}")
print(f"dtype de b = {b.dtype}")
# --------------------


A = 
 [[ 1.  1.  1.]
 [-1.  0.  1.]
 [ 1.  0.  1.]
 [ 1.  1.  1.]]
dtype de A = float64
b = [ 1.  1.  1. -1.]
dtype de b = float64


Introduce la matriz ampliada $(A\vert b)$, y calcula el rango de $A$ y de $(A\vert b).$

**Puntos = 0.5**

In [5]:
# Completar aquí
Ab = np.hstack((A, np.expand_dims(b, axis=1)))
print(f"Rango de A = {np.linalg.matrix_rank(A)}")
print(f"Rango de A|b = {np.linalg.matrix_rank(Ab)}")
# --------------------


Rango de A = 3
Rango de A|b = 4


Como los rangos son distintos, el sistema $Ax=b$ no tiene solución.

Aun así, vamos a calcular un vector $x_{-}$ que, de alguna manera, minimice la distancia entre $Ax_{-}$ y $b$.

Si usamos la factorización SVD de la matriz $A$, el sistema original $Ax=b$ se reescribe como 
$$
U S V^T x =b
$$
Así pues, calcula la factorización SVD de la matriz anterior $A$, es decir, encuentra matrices $U$, $S$ y $V$, de modo que $$A = U S V^T.$$ 

Has de imprimir por pantalla el producto $U S V^T$ para asegurarte que, salvo errores de redondeo y representación, se cumple que $A = U S V^T.$

Imprime también las dimensiones de las matrices $U$, $S$ y $V^T$.

**Puntos = 4**


In [6]:
# Completar aquí
U, s, VT = svd(A) # La matriz V que nos devuelve es la traspuesta
S = np.zeros((A.shape[0], A.shape[1]))
S[:A.shape[1], :A.shape[1]] = np.diag(s)

print(np.allclose(A, np.dot(U, np.dot(S, VT))))

print(f"Dimesión de U = {U.shape}")
print(f"Dimesión de S = {S.shape}")
print(f"Dimesión de V^T = {VT.shape}")
# --------------------


True
Dimesión de U = (4, 4)
Dimesión de S = (4, 3)
Dimesión de V^T = (3, 3)


Si $A$ fuera invertible, su inversa $A^{-1}$ sería
$$
A^{-1} = V S^{-1} U^T,
$$
pero como no lo es, se introduce la llamada **pseudo-inversa de Moore-Penrose de $A$** como la matriz siguiente:
$$
A_{-} = V S_{-} U^T
$$
donde $S_{-}$ es una matriz, en nuestro caso de tamaño $3\times 4$, que contiene en su diagonal principal los inversos de los valores singulares no nulos de $A$ y cero para aquellos valores singulares nulos. Nótese que si todos los valores singulares fuesen no nulos, entonces $S^{-1} = S_{-}$.

Se pide:

1) Introduce de manera manual $S_{-}$ e imprime por pantalla $S_{-}$ y el producto $S S_{-}$.

2) Calcula la pseudo-inversa de Moore-Penrose $A_{-}$  e imprímela por pantalla. 

**Puntos = 3**

In [7]:
# Completar aquí
V = VT.T
S_ = np.linalg.pinv(S)

print(f'S_ = \n{S_}')
print(f'\nSS_ = \n{S @ S_}')

A_manual = V @ S_ @ U.T

print(f"\nA_ = \n {A_manual}")
# --------------------


S_ = 
[[0.3660254  0.         0.         0.        ]
 [0.         0.70710678 0.         0.        ]
 [0.         0.         1.3660254  0.        ]]

SS_ = 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]

A_ = 
 [[-1.29557768e-16 -5.00000000e-01  5.00000000e-01 -2.06611345e-16]
 [ 5.00000000e-01 -1.64145597e-17 -1.00000000e+00  5.00000000e-01]
 [ 1.47967971e-17  5.00000000e-01  5.00000000e-01 -6.74562822e-18]]


La pseudo-inversa de Moore-Penrose está implementada en el método **pinv()** que se encuentra en el submódulo de Álgebra Lineal de NumPy. Acude a la API [numpy.linalg.pinv](https://numpy.org/doc/stable/reference/generated/numpy.linalg.pinv.html) y calcula la pseudo-inversa de $A$ haciendo uso de dicho método. 

Comprueba también, haciendo uso de un operador booleano, que una vez redondeadas a $8$ cifras decimales, con el método **np.round()** (véase [np.round](https://numpy.org/devdocs/reference/generated/numpy.round.html)), las dos pseudo-inversas que has calculado coinciden.

**Puntos = 1**

In [8]:
# Completar aquí
A_ = np.linalg.pinv(A)
print(f"A_ = \n {A_}")
# --------------------


A_ = 
 [[-9.69672317e-17 -5.00000000e-01  5.00000000e-01 -1.78855769e-16]
 [ 5.00000000e-01 -1.64145597e-17 -1.00000000e+00  5.00000000e-01]
 [ 5.09267711e-17  5.00000000e-01  5.00000000e-01  2.45493846e-17]]


In [9]:
np.allclose(np.round(A_manual, decimals=8), np.round(A_, decimals=8))

True

Finalmente, calcularemos $x_{-}$ y la distancia entre $Ax_{-}$ y $b$.


2) $x_{-} = A_{-} b$

3) El error entre $Ax_{-}$ y $b$, medido en la norma euclídea, es decir, error = $\Vert A x_{-} - b\Vert_2$. 

**Puntos = 1**


In [10]:
# Completar aquí
x_ = A_ @ b
error = np.linalg.norm(A @ x_ - b, 2)

print(f"x_ = {x_}")
print(f"error = {error}")
# --------------------


x_ = [ 5.55111512e-16 -1.00000000e+00  1.00000000e+00]
error = 1.4142135623730951
