# Práctica 7: Ejercicio para entregar. 
## Tensores en Ciencia de Datos.



El fichero la_manga.jpg contiene dos fotos de La Manga del Mar Menor, una de los años 60 y otra actual. 

![imagen de La Manga del Mar Menor en los años 60 y en la actualidad](../data/la_manga.jpg)

Carga dicho fichero y convierte la imagen en un tensor. A continuación, imprime por pantalla el tensor asociado a la imagen y guárdalo en la carpeta data con el nombre **tensor_la_manga.npy**



In [1]:
import numpy as np
from PIL import Image

In [2]:
# Completar aquí
img = Image.open('../data/la_manga.jpg')
imgarray = np.array(img)
print(f"Tensor asociado = \n{imgarray}")
# --------------------


Tensor asociado = 
[[[192 192 192]
  [190 190 190]
  [189 189 189]
  ...
  [149 176 195]
  [149 176 195]
  [149 176 195]]

 [[193 193 193]
  [191 191 191]
  [189 189 189]
  ...
  [148 175 194]
  [148 175 194]
  [148 175 194]]

 [[194 194 194]
  [192 192 192]
  [190 190 190]
  ...
  [146 173 192]
  [146 173 192]
  [146 173 192]]

 ...

 [[184 184 184]
  [143 143 143]
  [121 121 121]
  ...
  [ 59  89  81]
  [ 63  90  83]
  [ 61  91  83]]

 [[174 174 174]
  [133 133 133]
  [119 119 119]
  ...
  [ 63  94  86]
  [ 66  96  88]
  [ 66  97  89]]

 [[160 160 160]
  [123 123 123]
  [117 117 117]
  ...
  [ 67  98  90]
  [ 70 101  93]
  [ 70 101  93]]]


Calcula la forma y dimensión del tensor generado. 

In [3]:
# Completar aquí
print(f"Forma del tensor = {imgarray.shape}")
print(f"Dimensión del tensor = {imgarray.ndim}")
# --------------------


Forma del tensor = (720, 960, 3)
Dimensión del tensor = 3


Utiliza la técnica de **slicing** que vimos en la práctica 3 para generar dos vectores. Uno de ellos, denotado **v1** se ha de corresponder con la primera fila del tensor que ves por pantalla; el segundo vector, **v2**, está formado por la segunda fila que ves por pantalla.  

In [4]:
# Completar aquí
v1 = imgarray[0, 0, :]
v2 = imgarray[0, 1, :]
print(f"v1 = {v1}")
print(f"v2 = {v2}")
# --------------------


v1 = [192 192 192]
v2 = [190 190 190]


Calcula:

1) el producto tensorial de **v1** y **v2**

2) el producto de Hadamard de **v1** y **v2**

3) el producto escalar de **v1** y **v2**

In [5]:
# Completar aquí
print(f"v1 ⊗ v2 = \n{np.tensordot(v1, v2, axes=0)}")
print(f"v1 * v2 = {v1 * v2}")
print(f"Producto escalar de v1 y v2 = {np.tensordot(v1, v2, axes=1)}")
# --------------------


v1 ⊗ v2 = 
[[128 128 128]
 [128 128 128]
 [128 128 128]]
v1 * v2 = [128 128 128]
Producto escalar de v1 y v2 = 128


Introduce manualmente, usando **np.array()**, los vectores **v1** y **v2** anteriores y denótaos por **z1** y **z2**, respectivamente.

A contrinuación realiza los mismos cálculos (producto tensorial, producto de Hadamard y producto escalar) con los vectores **z1** y **z2**.

In [6]:
# Completar aquí
z1 = np.array([192, 192, 192])
z2 = np.array([190, 190, 190])

print(f"z1 ⊗ z2 = \n{np.tensordot(z1, z2, axes=0)}")
print(f"z1 * z2 = {z1 * z2}")
print(f"Producto escalar de z1 y z2 = {np.tensordot(z1, z2, axes=1)}")

# --------------------


z1 ⊗ z2 = 
[[36480 36480 36480]
 [36480 36480 36480]
 [36480 36480 36480]]
z1 * z2 = [36480 36480 36480]
Producto escalar de z1 y z2 = 109440


Como puedes ver, obtienes resultados distintos. 

Busca una explicación convincente para esta discrepancia de resultados.
Te puede resultar útil estudiar los atributos **shape**, **type** y **dtype** de los vectores **v1**, **v2**, **z1** y **z2**.

Investiga y dí todo lo que sepas sobre este asunto.

In [7]:
# Completar aquí
print("Forma (Shape)")
print(v1.shape)
print(v2.shape)
print(z1.shape)
print(z2.shape)
print()
print("Tipos")
print(type(v1))
print(type(v2))
print(type(z1))
print(type(z2))
print()
print("Tipo de Datos (dtype)")
print(v1.dtype)
print(v2.dtype)
print(z1.dtype)
print(z2.dtype)
# --------------------


Forma (Shape)
(3,)
(3,)
(3,)
(3,)

Tipos
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

Tipo de Datos (dtype)
uint8
uint8
int32
int32


### Discrepacia de resultados entre `v1`, `v2` y `z1`, `z2`

La discrepacia en los resultados se debe a la diferencia en los tipos de datos (`dtype`). Los tipos de datos afectan cómo se realizan las operaciones matemáticas en los tensores.
- `uint8` **vs** `int32`:
    - `uint8` representa enteros sin signo. Esto significa que no puede almacenar valores negativas y puede provocar un comportamiento inesperado en ciertas operaciones matemáticas, como desvordamiento.
    - `int32` representa enteros con signo. Puede almacenar valores negativos y tiene un rango mucho más amplio.