# Práctica 4: Ejercicio para entregar. 
## Vectores Y Matrices: aritmética y normas.



Los vectores y matrices de números complejos aparecen frecuentemente en Machine Learning. En concreto, en sistemas de reconocimiento del hablante (speech recognition) y más específicamente en la primera fase, donde se hace uso de una técnica de tratamiento de señales llamada **transformada discreta de Fourier**. En este ejercicio prácticaremos un poco con el tipo de vectores que aparecen en este campo.

Consideremos la llamada **matriz de la transformada de Fourier Discreta** en dimensión 4:
$$
DFT = \frac{1}{2}\left[\begin{array}{cccc}
1 & 1 & 1 & 1\\
1 & e^{2\pi j / 4} & e^{4\pi j / 4} & e^{6\pi j / 4}\\
1 & e^{4\pi j / 4} & e^{6\pi j / 4} & e^{8\pi j / 4}\\
1 & e^{6\pi j / 6} & e^{8\pi j / 8} & e^{10\pi j / 4}
\end{array}
\right]
$$
Nótese que las entradas de esta matriz tienen la forma $e^{2 k n \pi j/N}$, con  $n=0,1,2,3$, $N=4$ y $k = n^T$.

Introduce esta matriz siguiendo los siguiente pasos:

1) Introduce el escalar $N = 4$

2) Genera el vector $n = [0, 1, 2, 3]$ usando el método **arange**

3) Genera el vector $k = n^T$ usando el método **reshape**

4) Genera la matriz $n*k$

5) Genera la matriz con entradas $exp(2j * \pi * k * n / N)$



In [1]:
import numpy as np

In [3]:
# Completar aquí
N = 4
n = np.arange(N)
k = n.reshape((N, 1))
nk = n * k
DFT = np.exp(2j * np.pi * k * n / N)
print(f"N = {N}")
print(f"n = {n}")
print(f"k = \n{k}")
print(f"nk = \n{nk}")
print(f"DFT = \n{DFT}")
# --------------------


N = 4
n = [0 1 2 3]
k = 
[[0]
 [1]
 [2]
 [3]]
nk = 
[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]
 [0 3 6 9]]
DFT = 
[[ 1.0000000e+00+0.0000000e+00j  1.0000000e+00+0.0000000e+00j
   1.0000000e+00+0.0000000e+00j  1.0000000e+00+0.0000000e+00j]
 [ 1.0000000e+00+0.0000000e+00j  6.1232340e-17+1.0000000e+00j
  -1.0000000e+00+1.2246468e-16j -1.8369702e-16-1.0000000e+00j]
 [ 1.0000000e+00+0.0000000e+00j -1.0000000e+00+1.2246468e-16j
   1.0000000e+00-2.4492936e-16j -1.0000000e+00+3.6739404e-16j]
 [ 1.0000000e+00+0.0000000e+00j -1.8369702e-16-1.0000000e+00j
  -1.0000000e+00+3.6739404e-16j  5.5109106e-16+1.0000000e+00j]]


Utiliza la técnica de **slicing** estudiada en la práctica anterior para extraer la primer fila (que guardaremos en un vector denotado $v1$) y la tercera columna de la matriz $DFT$ (guardada en $v2$)


In [5]:
# Completar aquí
v1 = DFT[0, :]
v2 = DFT[:, 2]

print(f"v1 = {v1}")
print(f"v2 = {v2}")
# --------------------


v1 = [1.+0.j 1.+0.j 1.+0.j 1.+0.j]
v2 = [ 1.+0.0000000e+00j -1.+1.2246468e-16j  1.-2.4492936e-16j
 -1.+3.6739404e-16j]


 Calcula:

 1) $v1 + v2$

 2) $v1*v2$, componente a componente

 3) $v1 / v2$, componente a componente

 4) El producto escalar de $v1$ y $v2$

In [7]:
# Completar aquí
print(f"v1 + v2 = {v1 + v2}")
print(f"v1 * v2 = {v1 * v2}")
print(f"v1 / v2 = {v1 / v2}")
print(f"v1.v2 = {v1.dot(v2)}")
# --------------------


v1 + v2 = [2.+0.0000000e+00j 0.+1.2246468e-16j 2.-2.4492936e-16j 0.+3.6739404e-16j]
v1 * v2 = [ 1.+0.0000000e+00j -1.+1.2246468e-16j  1.-2.4492936e-16j
 -1.+3.6739404e-16j]
v1 / v2 = [ 1.+0.0000000e+00j -1.-1.2246468e-16j  1.+2.4492936e-16j
 -1.-3.6739404e-16j]
v1.v2 = 2.449293598294706e-16j


Calcula las normas $2$, $1$ y $\infty$ de $v1$

In [8]:
# Completar aquí
print(f"Norma 2 = {np.linalg.norm(v1, ord=2)}")
print(f"Norma 1 = {np.linalg.norm(v1, ord=1)}")
print(f"Norma ∞ = {np.linalg.norm(v1, ord=np.inf)}")
# --------------------


Norma 2 = 2.0
Norma 1 = 4.0
Norma ∞ = 1.0


Introduce una matriz D de 4 filas y 8 columnas de modo que la primera fila 
contenga tu número de DNI y el resto de filas números de DNI de algunos 
familiares tuyos.
Imprime también por pantalla la matriz D

In [9]:
# Completar aquí
D = np.array([
    [2, 6, 6, 4, 9, 1, 1, 0],
    [2, 2, 9, 8, 1, 6, 3, 0],
    [8, 7, 5, 9, 0, 1, 9, 4],
    [4, 2, 9, 4, 5, 0, 2, 2]
])
print(f"D = \n{D}")
# --------------------


D = 
[[2 6 6 4 9 1 1 0]
 [2 2 9 8 1 6 3 0]
 [8 7 5 9 0 1 9 4]
 [4 2 9 4 5 0 2 2]]


Calcula, usando las dos formas estudiadas en clase, e imprime por pantalla 
la matriz S = DD^T

In [11]:
# Completar aquí
print(f"S = \n{D @ D.T}")
print(f"S = \n{D.dot(D.T)}")
# --------------------


S = 
[[175 120 134 137]
 [120 199 180 136]
 [134 180 317 153]
 [137 136 153 150]]
S = 
[[175 120 134 137]
 [120 199 180 136]
 [134 180 317 153]
 [137 136 153 150]]


Introduce un vector b no nulo de dimensión 4, el que quieras, y calcula, de las 
dos formas que vimos en clase, el producto de S y b, es decir, S*b.
Calcula también b*S. Compara los resultados de S*b y b*S. 
¿Qué explicación encuentras de ambos resultados? 

In [13]:
# Completar aquí
b = np.array([1, 2, 3, 4])
S = D @ D.T # No lo había definido en el apartado anterior
print(f"S*b = {S @ b}")
print(f"S*b = {S.dot(b)}")
print(f"b*S = {b @ S}")
print(f"b*S = {b.dot(S)}")
# --------------------
"""
Al obtener los mismos resultados confirmamos que la opración es conmutativa
debido a la forma de los datos
"""

S*b = 
[1365 1602 2057 1468]
S*b = 
[1365 1602 2057 1468]
b*S = 
[1365 1602 2057 1468]
b*S = 
[1365 1602 2057 1468]


Calcula el producto de Hadamard de S y S. 
Calcula, componente a componente de S dividido por S.

In [14]:
# Completar aquí
print(f"(Producto de Hadamard) S º S = \n {S * S}")
print(f" S / S = \n {S / S}")
# --------------------


(Producto de Hadamard) S º S = 
 [[ 30625  14400  17956  18769]
 [ 14400  39601  32400  18496]
 [ 17956  32400 100489  23409]
 [ 18769  18496  23409  22500]]
 S / S = 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Comprueba que S es simétrica utilizando un operador Booleano

In [17]:
# Completar aquí
print(f"S es simétrica: {np.allclose(S, S.T)}") 
# La función 'np.allclose' se usa para evitar errores de redondeo
# print(f"S es simétrica: {S == S.T}") True
# Si hubiera números decimales no habría sido el caso aunque esta vez funcione
# --------------------


S es simétrica: True


Calcula la inversa de S, su traza, su determinante y su rango,

In [19]:
# Completar aquí
S_inv = np.linalg.inv(S)
traza = np.trace(S)
determinante = np.linalg.det(S)
rango = np.linalg.matrix_rank(S)
print(f"Matriz inversa = \n{S_inv}")
print(f"Traza = {traza}")
print(f"Determinante = {determinante}")
print(f"rango = {rango}")
# --------------------


Matriz inversa = 
[[ 0.02018033  0.00084963  0.00050182 -0.01971355]
 [ 0.00084963  0.0153955  -0.00391854 -0.01073768]
 [ 0.00050182 -0.00391854  0.00723647 -0.00428672]
 [-0.01971355 -0.01073768 -0.00428672  0.03877966]]
Traza = 841
Determinante = 77883125.99999991
rango = 4


## Ejercicio para hacer a mano

 Sean $u,v$ dos vectores no nulos vistos como matrices columna $n\times 1$. Observa que $1+v^{\top}u$ es un escalar, que suponemos no nulo. Prueba que la matriz $A = I+uv^{\top}$ es no singular y su inversa es
$$A^{-1}=I-\dfrac{uv^{\top}}{1+v^{\top}u}$$

Elige dos vectores $u= [1, 2, 3]$ y $v=[4, 5, 6]$ de $\mathbb{R}^3$ y comprueba en Python (no hace falta que lo hagas a mano) que se cumple la identidad anterior

In [38]:
# Completar aquí
u = np.array([1,2,3])
v = np.array([4,5,6])

uv_T = np.outer(u, v) # Producto exterior
I = np.eye(3)
A = I + uv_T
print(f"u * v.T = \n{uv_T}")
print(f"I = \n{I}")
print(f"A = \n{A}")

A_inv = I - uv_T / (1+ (v.T @ u))
print(f"A_inv = \n{A_inv}")
print(f"Comprobación: {np.allclose(np.linalg.inv(A), A_inv)}") 
# De esta forma comprobamos que A es no singular
# --------------------

u @ v.T = 
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
I = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
A = 
[[ 5.  5.  6.]
 [ 8. 11. 12.]
 [12. 15. 19.]]
A_inv = 
[[ 0.87878788 -0.15151515 -0.18181818]
 [-0.24242424  0.6969697  -0.36363636]
 [-0.36363636 -0.45454545  0.45454545]]
Comprobación: True
