# Práctica 3: Ejercicio para entregar. 
## NumPy arrays: index, slice, reshape, broadcasting, etc.



Introduce tu DNI en la forma de 1d-array.

A continuación, selecciona e imprime la siguiente información de dicho array:

1) el primer elemento
2) el último
3) El que ocupa la segunda posición (empezando desde la izquierda)
4) el que ocupa la antepenúltima 
5) los tres primeros elementos
6) los 4 últimos elementos

In [1]:
import numpy as np

In [2]:
# Completar aquí
dni = np.array([2, 6, 6, 4, 9, 1, 1, 0])
print(f"DNI = {dni}")
print(f"Primer elemento = {dni[0]}")
print(f"Último elemento = {dni[-1]}")
print(f"Segundo elemento = {dni[1]}")
print(f"Antepenúltimo elemento = {dni[-3]}")
print(f"Tres primeros elementos = {dni[0:3]}")
print(f"Cuatro último elementos = {dni[-4:]}")
# --------------------


DNI = [2 6 6 4 9 1 1 0]
Primer elemento = 2
Último elemento = 0
Segundo elemento = 6
Antepenúltimo elemento = 1
Tres primeros elementos = [2 6 6]
Cuatro último elementos = [9 1 1 0]


Cambia la forma del 1d-array que contiene tu nombre para convertirlo en un 2d-array (matriz) de tamaño $2\times 4$, es decir dos filas y cuatro columnas. 

A continuación, selecciona e imprime los siguientes datos del nuevo 2d-array:

1) la primera fila
2) la segunda columna

In [3]:
# Completar aquí
dni_matriz = dni.reshape(2, 4)
print(f"DNI_matriz = \n{dni_matriz}")
print(f"Primera fila = {dni_matriz[0]}")
print(f"Segunda columna = {dni_matriz[:, 1]}")

# --------------------


DNI_matriz = 
[[2 6 6 4]
 [9 1 1 0]]
Primera fila = [2 6 6 4]
Segunda columna = [6 1]


Imaginemos que el 2d-array del ejercicio anterior contiene las features $X$ y las labels $y$ de un modelo de Machine Learning. En concreto, $X$ almacena todos los datos excepto la última columna mientras que $y$ contiene los datos de la última columna.

Genera $X$ e $y$.

In [4]:
# Completar aquí
X = dni_matriz[:, :-1]
y = dni_matriz[:, -1]
print(f"X = \n{X}")
print(f"y = {y}")
# --------------------


X = 
[[2 6 6]
 [9 1 1]]
y = [4 0]


Supongamos ahora que queremos separar los datos del 2d-array en dos subconjuntos, un training dataset y un test dataset.

Training dataset será la primera fila y  test dataset será la segunda fila

In [5]:
# Completar aquí
train_dataset = dni_matriz[0, :]
test_dataset = dni_matriz[1, :]
print(f"train dataset = {train_dataset}")
print(f"test dataset = {test_dataset}")
# --------------------


train dataset = [2 6 6 4]
test dataset = [9 1 1 0]


Introduce un escalar que se corresponda con tu nota de entrada al grado de Ciencia e Ingeniería de Datos. A continuación realiza las siguientes operaciones:

1) Suma el escalar al 2d-array anterior
2) Multiplica el escalar al 2d-array anterior
3) Divide el 2d-array por el escalar

In [6]:
# Completar aquí
escalar = 11
print(f"escalar + dni_matriz = \n {dni_matriz + escalar}")
print(f"escalar * dni_matriz = \n {dni_matriz.dot(escalar)}")
print(f"dni_matriz / escalar = \n {dni_matriz / escalar}")
# --------------------


escalar + dni_matriz = 
 [[13 17 17 15]
 [20 12 12 11]]
escalar * dni_matriz = 
 [[22 66 66 44]
 [99 11 11  0]]
dni_matriz / escalar = 
 [[0.18181818 0.54545455 0.54545455 0.36363636]
 [0.81818182 0.09090909 0.09090909 0.        ]]
