# Práctica 8: Ejercicio para entregar. 
## Factorizaciones LU y Choleski. Aplicación a la resolución de sistemas lineales.



Una clase importante de matrices que aparecen muy frecuentemente en varios campos de la Ingeniería son las llamadas **matrices de Toeplitz**. En dimensión $5$, esta matriz es:
$$
T_5 = \left[\begin{array}{ccccc}
2 & -1 & 0 & 0 & 0\\
-1 & 2 & -1 & 0 & 0\\
0 & -1 & 2 & -1 & 0\\
0 & 0 & -1 & 2 & -1\\
0 & 0 & 0 & -1 & 2
\end{array}
\right]
$$


1) Introduce esta matriz en formato sparse y utilizando el método csr_matrix

2) Tranforma la matriz a formato dense y denota a la matriz resultante con la letra $T$



In [1]:
import numpy as np
from scipy.sparse import csr_matrix

In [2]:
# Completar aquí
x = csr_matrix([
    [2, -1, 0, 0, 0],
    [-1, 2, -1, 0, 0],
    [0, -1, 2, -1, 0],
    [0, 0, -1, 2, -1],
    [0, 0, 0, -1, 2]
])

T = x.todense()
print(f"T = \n{T}")
# --------------------


T = 
[[ 2 -1  0  0  0]
 [-1  2 -1  0  0]
 [ 0 -1  2 -1  0]
 [ 0  0 -1  2 -1]
 [ 0  0  0 -1  2]]


1) Comprueba, usando un operador booleano, que $T$ es simétrica

2) Comprueba que $T$ es no singular

3) Calcula el número de condicionamiento de $T$


In [3]:
# Completar aquí
print(f"1) {(T == T.T).all()}")
print(f"2) {np.linalg.det(T) != 0}")
print(f"3) {np.linalg.cond(T):.4f}")
# --------------------


1) True
2) True
3) 13.9282


Calcula la descomposición $PLU$ de $T$ y comprueba que $T = PLU$ 
haciendo uso de un operador booleano. 



In [4]:
# Completar aquí
from scipy.linalg import lu

P, L, U = lu(T)
print(f"T = \n{T}")
print(f"P = \n{P}")
print(f"L = \n{L}")
print(f"U = \n{U}")

print(f"¿T = PLU? {(T == P.dot(L.dot(U))).all()}")
# --------------------


T = 
[[ 2 -1  0  0  0]
 [-1  2 -1  0  0]
 [ 0 -1  2 -1  0]
 [ 0  0 -1  2 -1]
 [ 0  0  0 -1  2]]
P = 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
L = 
[[ 1.          0.          0.          0.          0.        ]
 [-0.5         1.          0.          0.          0.        ]
 [ 0.         -0.66666667  1.          0.          0.        ]
 [ 0.          0.         -0.75        1.          0.        ]
 [ 0.          0.          0.         -0.8         1.        ]]
U = 
[[ 2.         -1.          0.          0.          0.        ]
 [ 0.          1.5        -1.          0.          0.        ]
 [ 0.          0.          1.33333333 -1.          0.        ]
 [ 0.          0.          0.          1.25       -1.        ]
 [ 0.          0.          0.          0.          1.2       ]]
¿T = PLU? True


Calcula la factorización de Choleski de $T$

In [5]:
# Completar aquí
from scipy.linalg import ldl

L, D, P = ldl(T)

print(f"L = \n  {L}")
print(f"D = \n {D}")
print(f"P = \n  {P}")

LD = np.dot(L, D)
print(f"LD = \n {LD}")

print(f"LDL^T = \n {np.dot(LD, L.T)}")
# --------------------


L = 
  [[ 1.          0.          0.          0.          0.        ]
 [-0.5         1.          0.          0.          0.        ]
 [ 0.         -0.66666667  1.          0.          0.        ]
 [ 0.          0.         -0.75        1.          0.        ]
 [ 0.          0.          0.         -0.8         1.        ]]
D = 
 [[2.         0.         0.         0.         0.        ]
 [0.         1.5        0.         0.         0.        ]
 [0.         0.         1.33333333 0.         0.        ]
 [0.         0.         0.         1.25       0.        ]
 [0.         0.         0.         0.         1.2       ]]
P = 
  [0 1 2 3 4]
LD = 
 [[ 2.          0.          0.          0.          0.        ]
 [-1.          1.5         0.          0.          0.        ]
 [ 0.         -1.          1.33333333  0.          0.        ]
 [ 0.          0.         -1.          1.25        0.        ]
 [ 0.          0.          0.         -1.          1.2       ]]
LDL^T = 
 [[ 2. -1.  0.  0.  0.]
 [-1.

1) Resuelve el sistema $T^2x = b$, donde $b = \left[ 0, 0, -1, 0, 0\right]^T$

2) Comprueba mediante un operador booleano si $T^2x = b$. Explica a qué se debe el resultado que has obtenido y averigua la forma de resolverlo. Puede resultar útil usar el método np.round()

In [6]:
# Completar aquí
from scipy.linalg import solve

b = np.array([0,0,-1,0,0])

x = solve(T**2, b.T)
print(f"x = {x}")

print(np.all(T**2 @ x == b))

"""
Da como resultado "False" debido a errores de redondeo, si utilizo la función
np.round(), la igualdad sí es cierta.
"""

print(np.all(np.round(T**2 @ x) == np.round(b)))
# --------------------


x = [-2.25 -4.   -4.75 -4.   -2.25]
False
True
