# Práctica 2: Ejercicio para entregar 

## Introducción a N-dimensional arrays en Python


In [1]:
import numpy as np

Partimos de tu número de DNI, que debe contener 9 dígitos.
DNI = abcdefgh  . Por ejemplo, DNI = 23982606

Introduce tu DNI en forma de 1d-array e imprimelo junto con sus atributos forma, tamaño y tipo

In [2]:
# Completar aquí
dni = np.array([2,6,6,4,9,1,1,0])
print(f"DNI: {dni}")
print(dni.shape)
print(dni.size)
print(dni.dtype)

# --------------------


DNI: [2 6 6 4 9 1 1 0]
(8,)
8
int64


Define e imprimer los siguientes ndarrays:

1) Una matriz cuadrada de unos y de tamaño el dígito más grande de tu DNI.

2) Una matriz de tamaño $m\times n$, donde $m$ es el dígito más pequeño (excluido el $0$) de tu DNI, y $n$ el dígito más grande, cuyas entradas sean todo cero.

3) Un vector cuyo primer elemento sea el dígito más pequeño de tu DNI, cuyo último elemento sea el dígito más grande, y que contenga $5$ elementos equiespaciados.

4) Un vector cuyo primer elemento sea el dígito más pequeño de tu DNI, el último el dígito más grande y donde cada elemento del array esté separado del siguiente en una unidad. 

In [10]:
# Completar aquí
n = max(dni)
m = min([x for x in dni if x != 0]) # Con este bucle y condición se evita que tome el 0 como más pequeño
ones = np.ones([n, n])
zeros = np.zeros([m, n])
vector1 = np.linspace(m, n, 5)
vector2 = np.arange(m, n+1) # Este ajuste evita el mismo problema que tendríamos con una lista
print(f'M_unos = \n {ones}')
print(f'M_zeros = {zeros}')
print(f'Vector 1 = {vector1}')
print(f'Vector 2 = {vector2}')
# --------------------


M_unos = 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
M_zeros = [[0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Vector 1 = [1. 3. 5. 7. 9.]
Vector 2 = [1 2 3 4 5 6 7 8 9]


Apila de manera horizontal los vectores introducidos en los apartados 3) y 4) del apartado anterior.

Calcula el tamaño el array resultante.

In [12]:
# Completar aquí
vector3 = np.hstack((vector1, vector2))
print(f'Vector 3 = {vector3}')
print(vector3.size)
# --------------------


Vector 3 = [1. 3. 5. 7. 9. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
14



Utiliza **vstack** para generar una matriz con dos filas, cada una de las cuales contenga al vector gnerado en el apartado 4) anterior.

Calcula el tipo o forma (shape) del array generado.

In [13]:
# Completar aquí
matrix = np.vstack((vector2, vector2))
print(f'Matriz resultante = \n{matrix}')
print(matrix.shape)
# --------------------


Matriz resultante = 
[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]
(2, 9)


Intenta apilar, también de manera vertical, los vectores de los apartados 3) y 4) anteriores. 

Obtienes un error. ¿A qué se debe este error?

In [14]:
# Completar aquí
matrix2 = np.vstack((vector1, vector2))
# El error se debe a una diferencia en las dimensiones de ambos vectores
# --------------------


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 9

Introduce tu DNI en formato lita y tupla. Convierte ambos a formato **ndarray** 

In [21]:
# Completar aquí
dni_list = [2,6,6,4,9,1,1,0]
dni_tuple = (2,6,6,4,9,1,1,0)
dni_list_ndarray = np.array(dni_list)
dni_tuple_ndarray = np.array(dni_tuple)
print(f"Lista DNI: {dni_list}")
print(type(dni_list))
print(f"Lista DNI en formato ndarray: {dni_list_ndarray}")
print(type(dni_list_ndarray))
print(f"Tupla DNI: {dni_tuple}")
print(type(dni_tuple))
print(f"Tupla DNI en formato ndarray: {dni_tuple_ndarray}")
print(type(dni_tuple_ndarray))
# --------------------


Lista DNI: [2, 6, 6, 4, 9, 1, 1, 0]
<class 'list'>
Lista DNI en formato ndarray: [2 6 6 4 9 1 1 0]
<class 'numpy.ndarray'>
Tupla DNI: (2, 6, 6, 4, 9, 1, 1, 0)
<class 'tuple'>
Tupla DNI en formato ndarray: [2 6 6 4 9 1 1 0]
<class 'numpy.ndarray'>
