# Práctica 9: Ejercicio para entregar. 
## Métodos iterativos para la resolución de sistemas lineales


Consideremos la matriz de Toeplitz en dimensión $n$:
$$
K_n = \left[
    \begin{array}{ccccccc}
    2 & -1 & 0 & 0 & 0 & \cdots & 0 \\ 
    -1 & 2 & -1 & 0 & 0 &\cdots & 0 \\
    0 & -1 & 2 & -1 & 0 &\cdots & 0 \\
    \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots \\
    0 & 0 & 0 & \cdots & -1 & 2 & -1\\
    0 & 0 & 0 & \cdots & 0 & -1 & 2\\
    \end{array}
    \right]
$$

Define una función cuya entrada sea $n$, y cuya salida sea la matriz de Toeplitz en dimensión $n$. Has de usar los métodos de Python sobre matrices **sparse**, en concreto **csr_matrix**.

Ejecuta dicha función para el caso $n=6$ e imprime el resultado en pantalla y en forma matriz densa, para asegurarte que está bien implmentada.

In [1]:
# Completar aquí
import numpy as np
from scipy.sparse import csr_matrix

def MatrizToeplitz(n):
    FilaIndex = np.zeros(4 + (n-2)*3, dtype=int)
    ColumnIndex = np.zeros(4 + (n-2)*3, dtype=int)
    Data = np.zeros(4 + (n-2)*3, dtype=int)

    FilaIndex[0] = 0  # Cambiar a 0 ya que las matrices en Python son de base 0
    ColumnIndex[0] = 0
    Data[0] = 2

    FilaIndex[1] = 0
    ColumnIndex[1] = 1
    Data[1] = -1

    FilaIndex[2 + 3*(n-2)] = n - 1
    ColumnIndex[2 + 3*(n-2)] = n - 2
    Data[2 + 3*(n-2)] = -1

    FilaIndex[2 + 3*(n-2) + 1] = n - 1
    ColumnIndex[2 + 3*(n-2) + 1] = n - 1
    Data[2 + 3*(n-2) + 1] = 2

    for i in range(2, n):
        FilaIndex[2 + (i-2)*3] = i - 1
        FilaIndex[2 + (i-2)*3 + 1] = i - 1
        FilaIndex[2 + (i-2)*3 + 2] = i - 1

        ColumnIndex[2 + (i-2)*3] = i - 2
        ColumnIndex[2 + (i-2)*3 + 1] = i - 1
        ColumnIndex[2 + (i-2)*3 + 2] = i

        Data[2 + (i-2)*3] = -1
        Data[2 + (i-2)*3 + 1] = 2
        Data[2 + (i-2)*3 + 2] = -1

    toeplitz = csr_matrix((Data, (FilaIndex, ColumnIndex)), shape=(n, n))
    return toeplitz

# Ejemplo de uso
n = 6
print(f'Matriz en formato sparse: \n {MatrizToeplitz(n)}')
print(f'Matriz en formato dense: \n {MatrizToeplitz(n).todense()}')
# --------------------


Matriz en formato sparse: 
   (np.int32(0), np.int32(0))	2
  (np.int32(0), np.int32(1))	-1
  (np.int32(1), np.int32(0))	-1
  (np.int32(1), np.int32(1))	2
  (np.int32(1), np.int32(2))	-1
  (np.int32(2), np.int32(1))	-1
  (np.int32(2), np.int32(2))	2
  (np.int32(2), np.int32(3))	-1
  (np.int32(3), np.int32(2))	-1
  (np.int32(3), np.int32(3))	2
  (np.int32(3), np.int32(4))	-1
  (np.int32(4), np.int32(3))	-1
  (np.int32(4), np.int32(4))	2
  (np.int32(4), np.int32(5))	-1
  (np.int32(5), np.int32(4))	-1
  (np.int32(5), np.int32(5))	2
Matriz en formato dense: 
 [[ 2 -1  0  0  0  0]
 [-1  2 -1  0  0  0]
 [ 0 -1  2 -1  0  0]
 [ 0  0 -1  2 -1  0]
 [ 0  0  0 -1  2 -1]
 [ 0  0  0  0 -1  2]]


Genera dos ficheros con extensión .py

El primero de ellos se ha de llamar jacobi.py y ha de contener la función jacobi que está en la práctica 9. El segundo se ha de llamar gauss_seidel.py y ha de contener la función gauss_seidel de la misma práctica.

Importa ambas funciones a este fichero. Por ejemplo, para jacobi.py, esto se hace así: **from jacobi import jacobi**. Lo mismo para gauss-seidel.

In [2]:
# Completar aquí
from jacobi import jacobi
from gauss_seidel import gauss_seidel
# --------------------


Toma $n$ igual a las dos últimas cifras de tu DNI y genera un 1d-array (vector) de dimensión $n$ con todas sus componentes igual a 1. Denótalo $b$.

Se muestran a continuación los resultados para $n=66$.

In [3]:
# Completar aquí
n = 10
b = np.ones(n)
print(f"b = {b}")
print(np.ones(66))
# --------------------


b = [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Para el valor de $n$ que has tomado anteriormente, resuelve el sistema $K_n x = b$ mediante ambos, los métodos de Jacobi y Gauss-Seidel, y haciendo uso de las funciones que acabas de importar.



In [4]:
# Completar aquí
K = MatrizToeplitz(n).todense()
x_jacobi = jacobi(K, b)
x_gaus_seidel = gauss_seidel(K, b)
print(f"Utilizando el método de Jacobi: x = \n{x_jacobi}")
print(f"Utilizando el método de Gauss-Seidel: x = \n{x_gaus_seidel}")
# --------------------


Utilizando el método de Jacobi: x = 
[ 4.99999999  8.99999998 11.99999997 13.99999997 14.99999997 14.99999997
 13.99999997 11.99999997  8.99999998  4.99999999]
Utilizando el método de Gauss-Seidel: x = 
[ 4.99999999  8.99999999 11.99999999 13.99999998 14.99999998 14.99999998
 13.99999999 11.99999999  8.99999999  5.        ]


Calcula las normas 2 e infinito de la diferencia de ambas soluciones

In [5]:
# Completar aquí
print(f"Norma 2 = {np.linalg.norm(x_jacobi - x_gaus_seidel, ord=2)}")
print(f"Norma infinito = {np.linalg.norm(x_jacobi - x_gaus_seidel, ord=np.inf)}")
# --------------------


Norma 2 = 4.1457714793631194e-08
Norma infinito = 1.78402892458962e-08
