# Práctica 10: Ejercicio para entregar. 
## Autovalores y autovectores en Python


Algunos problemas en Data Science requieren el cálculo de valor propio dominante (el más grande) de una matriz. 

En este ejercicio implementaremos el llamado **Método de la Potencia** para el cálculo de dicho valor propio dominante. Aplicaremos dicho método a una **matriz de Markov** y compararemos los resultados obtenidos con el método **eig** implementado por defecto en Python.



Partimos de una matriz $M$. En este caso, una matriz cuadrada cuyas entradas son positivas y de modo que, para cada columna, si sumamos sus entradas, el resultado es $1$. Este tipo de matrices se llaman de **Markov** y tienen aplicaciones en Álgebra Lineal, Estadística e Informática. Por ejemplo, la siguiente matriz de orde $2$ es de Markov:

$$
M_2 = \left[
    \begin{array}{cc}
    0.2 & 0.4 \\ 
    0.8 & 0.6 \\
    \end{array}
    \right]
$$



Introduce una matriz de Markov de orden $4$, la que tú quieras, y denótala por $M$.

In [1]:
import numpy as np

In [2]:
# Completar aquí
M = np.array([
    [0.1, 0.3, 0.4, 0.2],
    [0.2, 0.1, 0.3, 0.4],
    [0.3, 0.4, 0.2, 0.1],
    [0.4, 0.2, 0.1, 0.3]
])
# --------------------

El método de la potencia es un método iterativo donde se parte incialmente de un vector (el llamado **initial guess**). 

Introducimos un vector (1d-array) con cuatro componentes, por ejemplo $v = (0.5, 0.5, 0.5, 0.5)$.

In [3]:
# Completar aquí
v = np.array([0.5,0.5,0.5,0.5])
# --------------------


A continuación vamos a implementar un bucle (loop) con $11$ iteraciones donde en cada iteración vamos a hacer lo siguiente:

1) Multiplicamos $M$ y $v$ y volvemos a denotar por $v$ el resultado, es decir,
**v = M v**.

2) Calculamos la mayor, en valor absoluto, de las componentes de **v**. Recuerda, el valor absoluto de un vector se calcula con **abs** y el máximo aplicando el método **max()**. Denotamos por **lambda** al resultado. Esto nos da una aproximación del valor propio dominante.

3) Dividimos **v** por la mayor de sus componentes. Esto nos da una aproximación del vector propio asociado al valor propio dominante

4) Imprimimos los resultados de 2) y 3) en cada iteración.

In [4]:
# Completar aquí
for i in range(11):
    v = M @ v

    Lambda = np.max(np.abs(v))
    # El programa no permite que escriba "lambda", por eso está escrito con
    # mayúsculas

    v = v / Lambda

    print(f"Iteración {i + 1}: Valor propio dominante (lambda) = {Lambda}")
    print(f"Vector propio asociado: {v}")
    print("------------------------")
# --------------------


Iteración 1: Valor propio dominante (lambda) = 0.5
Vector propio asociado: [1. 1. 1. 1.]
------------------------
Iteración 2: Valor propio dominante (lambda) = 1.0
Vector propio asociado: [1. 1. 1. 1.]
------------------------
Iteración 3: Valor propio dominante (lambda) = 1.0
Vector propio asociado: [1. 1. 1. 1.]
------------------------
Iteración 4: Valor propio dominante (lambda) = 1.0
Vector propio asociado: [1. 1. 1. 1.]
------------------------
Iteración 5: Valor propio dominante (lambda) = 1.0
Vector propio asociado: [1. 1. 1. 1.]
------------------------
Iteración 6: Valor propio dominante (lambda) = 1.0
Vector propio asociado: [1. 1. 1. 1.]
------------------------
Iteración 7: Valor propio dominante (lambda) = 1.0
Vector propio asociado: [1. 1. 1. 1.]
------------------------
Iteración 8: Valor propio dominante (lambda) = 1.0
Vector propio asociado: [1. 1. 1. 1.]
------------------------
Iteración 9: Valor propio dominante (lambda) = 1.0
Vector propio asociado: [1. 1. 1. 1.]

Comprueba que, en efecto, se cumple que $M v = \lambda v$, para $\lambda$ el autovalor dominante que acabas de calcular y $v$ su autovector asociado. 

In [5]:
# Completar aquí
for i in range(11):
    v = M @ v

    Lambda = np.max(np.abs(v))
    # El programa no permite que escriba "lambda", por eso está escrito con
    # mayúsculas

    v = v / Lambda

    print(f"Verificación {i+1} Mv = lambda v: {np.allclose(M @ v, Lambda * v)}")
    print("------------------------")
# --------------------


Verificación 1 Mv = lambda v: True
------------------------
Verificación 2 Mv = lambda v: True
------------------------
Verificación 3 Mv = lambda v: True
------------------------
Verificación 4 Mv = lambda v: True
------------------------
Verificación 5 Mv = lambda v: True
------------------------
Verificación 6 Mv = lambda v: True
------------------------
Verificación 7 Mv = lambda v: True
------------------------
Verificación 8 Mv = lambda v: True
------------------------
Verificación 9 Mv = lambda v: True
------------------------
Verificación 10 Mv = lambda v: True
------------------------
Verificación 11 Mv = lambda v: True
------------------------


Comparamos ahora los resultados obtenidos con los que provienen del método **eig** implementado en el submódulo **np.linalg** de Python



In [6]:
# Completar aquí
autovalores, autovectores = np.linalg.eig(M)
print(f"Autovalores de M: \n{autovalores}")
print()
print(f"Autovectores de M: \n {autovectores}")
# --------------------


Autovalores de M: 
[ 1.00000000e+00 -3.00000000e-01 -4.96753436e-09  4.96753434e-09]

Autovectores de M: 
 [[ 0.5        -0.31622777  0.5        -0.5       ]
 [ 0.5        -0.63245553 -0.50000001  0.49999999]
 [ 0.5         0.63245553  0.5        -0.5       ]
 [ 0.5         0.31622777 -0.49999999  0.50000001]]


Identificamos el valor propio dominante con valor $\lambda_{max} = 1$. Pero los autovectores, ¿dónde están? ¿dónde está el vector propio asociado a $\lambda_{max}$?

Una pista: investiga la primera columna de la salida anterior.

In [7]:
# Completar aquí
lambda_max = 1
v_max = autovectores[:, 0]

# El vector propio asociado se encuentra la primera columna de vectores

print(v_max)
# --------------------


[0.5 0.5 0.5 0.5]
