---
title: "Visualización de Datos"
subtitle: "**Numpy:** Manejo de arrays mediante librería NumpPy"
author: "Francisco Javier Mercader Martínez"
format:
    pdf:
        documentclass: article
        hightlight-style: tango
---

In [1]:
!pip install numpy

In [5]:
import numpy
print(numpy.__version__)

1.26.4


In [6]:
import numpy as np
print(np.__version__)

1.26.4


In [8]:
np.array([1,2,3,4], dtype='float32')
np.array([1,2,3,4], dtype='int')

array([1, 2, 3, 4])

In [9]:
np.array([[1,2,3], [4,5,6], [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.array([range(i, i + 3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])