# Practica 11: Factorización SVD (Singular Value Decomposition)

In [1]:
import numpy as np
from scipy.linalg import svd

In [2]:
A = np.array([
    [0, 1, -1],
    [1, 1, 0],
])

U, s, V = svd(A)
print(f"U = \n {U}")
print(f"s = {s}")
print(f"V = \n {V}") #Lo que devuelve es directamente la traspuesta


U = 
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
s = [1.73205081 1.        ]
V = 
 [[ 4.08248290e-01  8.16496581e-01 -4.08248290e-01]
 [ 7.07106781e-01  2.26762120e-16  7.07106781e-01]
 [-5.77350269e-01  5.77350269e-01  5.77350269e-01]]


In [3]:
# Comprobación
S = np.zeros((2, 3), dtype=float)
print(S)
S[:2, :2] = np.diag(s)
print(f"S = \n {S}")

print(f"USV^T = \n {U.dot(S.dot(V))}")

#Comprobación personal
np.round(U.dot(S.dot(V)))

[[0. 0. 0.]
 [0. 0. 0.]]
S = 
 [[1.73205081 0.         0.        ]
 [0.         1.         0.        ]]
USV^T = 
 [[-5.48888227e-17  1.00000000e+00 -1.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00 -1.01465364e-17]]


array([[-0.,  1., -1.],
       [ 1.,  1., -0.]])

## Aplicación de la SVD a la reducción de la dimensión (PCA)

In [4]:
A = np.array([
    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
])
print(f"A = \n {A}")

A = 
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


In [5]:
U, s, V = svd(A)
print(f"V = \n {V}")

Sigma = np.zeros((A.shape[0], A.shape[1]))
Sigma[:A.shape[0], :A.shape[0]] = np.diag(s)
print(f"Sigma = \n {Sigma}")

V = 
 [[-0.24139304 -0.25728686 -0.27318068 -0.2890745  -0.30496832 -0.32086214
  -0.33675595 -0.35264977 -0.36854359 -0.38443741]
 [ 0.53589546  0.42695236  0.31800926  0.20906617  0.10012307 -0.00882003
  -0.11776313 -0.22670623 -0.33564933 -0.44459242]
 [ 0.09975293 -0.01037753  0.23987452  0.05273845  0.0996209  -0.46517509
  -0.52300449 -0.23591804  0.593137    0.14935136]
 [-0.259848   -0.19489762 -0.10988774  0.9273013  -0.07153728 -0.05251768
  -0.04829915 -0.05415057 -0.07582496 -0.0603383 ]
 [-0.26312174 -0.0585767  -0.12150761 -0.05740164  0.9302533  -0.0441965
  -0.05005435 -0.07728074 -0.13808364 -0.12003039]
 [-0.34412869 -0.09157816  0.43274424 -0.05958094 -0.05492318  0.70339002
  -0.33412339 -0.23272698  0.08693936 -0.10601229]
 [-0.3607094   0.01575684  0.51799467 -0.04727562 -0.05090152 -0.33292338
   0.61579275 -0.27850803  0.07385978 -0.15308609]
 [-0.33345757  0.21857007  0.28415895 -0.02511566 -0.05422893 -0.22221261
  -0.27509879  0.75032187 -0.10121342 -0.24172

In [6]:
# Reducimos la dimensión a los dos primeros valores singulares
n_componentes = 2
Sigma = Sigma[:, :n_componentes]
print(f"Sigma reducida = \n {Sigma}")

V = V[:n_componentes, :]
print(f"V = \n {V}")

Sigma reducida = 
 [[96.96573419  0.        ]
 [ 0.          7.25578339]
 [ 0.          0.        ]]
V = 
 [[-0.24139304 -0.25728686 -0.27318068 -0.2890745  -0.30496832 -0.32086214
  -0.33675595 -0.35264977 -0.36854359 -0.38443741]
 [ 0.53589546  0.42695236  0.31800926  0.20906617  0.10012307 -0.00882003
  -0.11776313 -0.22670623 -0.33564933 -0.44459242]]


In [7]:
T = U.dot(Sigma)
print(f"T = \n {T}") 
# T reemplaza a la matriz original A pues contiene la escala de los datos de A.

T = 
 [[-18.52157747  -6.47697214]
 [-49.81310011  -1.91182038]
 [-81.10462276   2.65333138]]
