# Práctica 8: Factorizaciones LU y Cholesky. Resolución de sistemas lienales mediante métodos directos

## Factorizaciones LU y Cholesky

In [2]:
import numpy as np
from scipy.linalg import lu


In [4]:
A = np.array([
    [4, -3, -5],
    [-2, -4, 5],
    [8, 8, 2]
])
print(f"A = \n {A}")
# Calculamos la factorización PLU (matriz de permutación)

P, L, U = lu(A)
print(f"P = \n {P}")
print(f"L = \n {L}")
print(f"U = \n {U}")

A = 
 [[ 4 -3 -5]
 [-2 -4  5]
 [ 8  8  2]]
P = 
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L = 
 [[ 1.          0.          0.        ]
 [ 0.5         1.          0.        ]
 [-0.25        0.28571429  1.        ]]
U = 
 [[ 8.          8.          2.        ]
 [ 0.         -7.         -6.        ]
 [ 0.          0.          7.21428571]]


In [13]:
# Comprobación
PLU = np.dot(L, U)
print(f"PLU = \n {PLU}")

PLU == np.dot(L, U)

A == A.T

PLU = 
 [[ 8.  8.  2.]
 [ 4. -3. -5.]
 [-2. -4.  5.]]


array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [16]:
# Factorización Cholesky para matrices simétricas y definidas positivas 
T = np.array([
    [2, -1, 0],
    [-1, 2, -1],
    [0, -1, 2]    
])

print(f"T = \n {T}")

from scipy.linalg import ldl

L, D, P = ldl(T) # P es una matriz de permutación

print(f"L = \n  {L}")
print(f"D = \n {D}")
print(f"P = \n  {P}")

LD = np.dot(L, D)
print(f"LD = \n {LD}")

print(f"LDL^T = \n {np.dot(LD, L.T)}")

T = 
 [[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]
L = 
  [[ 1.          0.          0.        ]
 [-0.5         1.          0.        ]
 [ 0.         -0.66666667  1.        ]]
D = 
 [[2.         0.         0.        ]
 [0.         1.5        0.        ]
 [0.         0.         1.33333333]]
P = 
  [0 1 2]


## Métodos directos para la resolución de sistemas lineales $Ax = b$

In [17]:
from scipy.linalg import solve

In [18]:
# A es la matriz del principio
b = np.array([2, -5, -3])

x = solve(A, b)
print(f"x = {x}")

x = [-0.44306931  0.3019802  -0.93564356]
