# Práctica 3: Más cosas sobre NumPy arrays: index, slice, reshape, broadcasting

## Array index

In [1]:
import numpy as np 

In [2]:
data = np.array([11, 22, 33, 44, 55])
print(f"data = {data}")
print(data[0])
print(data[4])
print(data[-1])

data = [11 22 33 44 55]
11
55
55


In [3]:
# 2d-array
data = np.array([
    [11, 22], 
    [33, 44],
    [55, 66]
])
print(f"data = \n {data}")
print(data[0, 0])
print(data[:, 1]) # : -> from : to 
print(data[0, :]) # selecciona todos los datos de la fila indicada

data = 
 [[11 22]
 [33 44]
 [55 66]]
11
[22 44 66]
[11 22]


## Array sciling

In [4]:
data = np.array([11, 22, 33, 44, 55, 66])
print(data[1:4])
print(data[-2:]) #empieza en la posción indicada desde el final de la lista

[22 33 44]
[55 66]


In [5]:
data = np.array([
    [11, 22, 33],
    [44, 55, 66],
    [77, 88, 99]
])
print(f"data = \n {data}")
x, y = data[:, :-1], data[:, -1]
print(f"features X = \n {x}")
print(f"labels = {y}")
#todos los datos se dividen en columnas X (features) y datos Y (labels)

data = 
 [[11 22 33]
 [44 55 66]
 [77 88 99]]
features X = 
 [[11 22]
 [44 55]
 [77 88]]
labels = [33 66 99]


In [6]:
split = 2
train, test = data[:split,:], data[split:, :]
print(f"training dataset = \n {train}")
print(f"test dataset = {test}")

training dataset = 
 [[11 22 33]
 [44 55 66]]
test dataset = [[77 88 99]]


## Reshape