# Práctica: Introducción a NumPy arrays

[API_ndarray](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)

In [1]:
import numpy as np 

In [2]:
# vectores en NumPy (1d-array)
v = np.array([1, 2, 3])
print (v)
# algunos atributos
print(type(v))
print(v.shape)
print(v.size)
print(v.dtype)

[1 2 3]
<class 'numpy.ndarray'>
(3,)
3
int32


In [3]:
#matrices
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(f"A = \n {A}")
print(A.shape)

A = 
 [[1 2 3]
 [4 5 6]]
(2, 3)


In [4]:
# algunos métodos habituales
a = np.zeros([4, 7])
print(a)
b = np.ones([4])
print(b)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[1. 1. 1. 1.]


In [5]:
c = np.arange(1, 5, 0.5)
print(c)
z = np.ones(4, dtype=complex) * 2
print(z)
d = np.linspace(0, 1, 10)
print(d)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[2.+0.j 2.+0.j 2.+0.j 2.+0.j]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


# Apilamiento de Vectores

In [6]:
# vertical (vstack)
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
a3 = np.vstack((a1, a2))
print(f"a3 \n {a3}")
print(a1.shape)
print(a3.shape)

a3 
 [[1 2 3]
 [4 5 6]]
(3,)
(2, 3)


In [7]:
# Horizontal hstack
a4 = np.hstack((a1, a2))
print(f"a4 \n {a4}")
print(a4.shape)

a4 
 [1 2 3 4 5 6]
(6,)


In [8]:
# listas en Python
lista = [1, 2, 3]
print(lista)
print(type(lista))
# transformamos lsitas en ndarray
vector = np.array(lista)
print(vector)
print(type(vector))

[1, 2, 3]
<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>


In [9]:
# tuplas
tupla = (1, 2, 3)
print(tupla)
print(type(tupla))
# transformamos tuplas en ndarray
vector2 = np.array(tupla)
print(type(vector))
print(vector)

(1, 2, 3)
<class 'tuple'>
<class 'numpy.ndarray'>
[1 2 3]
