# Práctica 10: Factorización QR. Aplicación al cálculo de valores y vectores propios

In [171]:
import numpy as np

## Factorización QR

In [172]:
A = np.random.randn(4, 3) #Imprime una matriz de números aleatorios
print(f"A = \n {A}")

A = 
 [[ 0.63544686 -0.77827159 -1.11306111]
 [-1.19184696  0.95797135 -1.63111002]
 [ 0.33819971  0.88283047 -0.66243503]
 [ 1.1502787  -0.19730051  1.5334664 ]]


In [173]:
# Calculamos la factorización QR de A
Q, R = np.linalg.qr(A) #La función ya viene implementada en Python
print(f"Q = \n  {Q}") 
print(f"R = \n {R}") 


Q = 
  [[-0.3518437   0.37533304  0.83507092]
 [ 0.6599196  -0.30620097  0.26828531]
 [-0.18725946 -0.82848794  0.37916116]
 [-0.63690347 -0.28102278 -0.29481582]]
R = 
 [[-1.80604873  0.86635704 -1.53740078]
 [ 0.         -1.26141126  0.19955931]
 [ 0.          0.         -2.07034761]]


In [174]:
# Comprobamos que A es igual a Q·R
np.allclose(A, np.dot(Q, R)) #allclose aproxima los valores de redondeo 

True

## Algoritmo QR para el cálculo de valores y vectores propios

In [175]:
from numpy.linalg import eig

In [176]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

autovalores, autovectores = eig(A)
print(f"Autovalores \n {autovalores}")
print(f"Autovectores = \n {autovectores}")

Autovalores 
 [ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]
Autovectores = 
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [177]:
# Comprobación
B = A.dot(autovectores[:, 2])
print(B)
C = autovectores[:, 2] * autovalores[2]
print(C)



[-4.44089210e-16 -8.88178420e-16 -1.77635684e-15]
[-1.38164941e-16  2.76329881e-16 -1.38164941e-16]


Comprobamos la factorización de A en valores propios, es decir, 
$$
A = P D P^{-1}
$$

In [178]:
D = np.diag(autovalores)
P = autovectores
from numpy.linalg import inv
inv_P = inv(P)
print(f"PDP^{-1} = \n {P.dot(D).dot(inv_P)}")

PDP^-1 = 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## Algoritmo QR para el cálculo de valores y vectores propios

In [179]:
from numpy.linalg import qr

In [180]:
A = np.array([
    [0, 2],
    [2, 3]
])
# Q, R = qr(A)
p = [1, 5, 10, 20, 40]
for i in range(40):
    Q, R = qr(A)
    A = R.dot(Q)
    if i+1 in p:
        print(f"Iteración {i+1}:")
        print(f"A = \n {A}")
        print(f"Q = \n {Q}")

Iteración 1:
A = 
 [[3. 2.]
 [2. 0.]]
Q = 
 [[ 0. -1.]
 [-1.  0.]]
Iteración 5:
A = 
 [[ 3.99998093  0.00976559]
 [ 0.00976559 -0.99998093]]
Q = 
 [[-0.99995232 -0.00976531]
 [-0.00976531  0.99995232]]
Iteración 10:
A = 
 [[ 4.00000000e+00  9.53674316e-06]
 [ 9.53674316e-06 -1.00000000e+00]]
Q = 
 [[-1.00000000e+00 -9.53674316e-06]
 [-9.53674316e-06  1.00000000e+00]]
Iteración 20:
A = 
 [[ 4.00000000e+00  9.09484252e-12]
 [ 9.09494702e-12 -1.00000000e+00]]
Q = 
 [[-1.00000000e+00 -9.09494702e-12]
 [-9.09494702e-12  1.00000000e+00]]
Iteración 40:
A = 
 [[ 4.00000000e+00 -1.04494923e-16]
 [ 8.27180613e-24 -1.00000000e+00]]
Q = 
 [[-1.00000000e+00 -8.27180613e-24]
 [-8.27180613e-24  1.00000000e+00]]


In [183]:
autovalores1, autovectores1 = eig(A)
print(f"Autovalores = {autovalores1}")
print(f"Autovectores = \n {autovectores1}")

Autovalores = [ 4. -1.]
Autovectores = 
 [[1.00000000e+00 2.08989846e-17]
 [0.00000000e+00 1.00000000e+00]]
