# Práctica 6. Matrices sparse. Manipulación de matrices desde ficheros de datos

##  [Matrices sparse](https://docs.scipy.org/doc/scipy/reference/sparse.html)



In [1]:
import numpy as np
from scipy.sparse import csr_matrix

In [4]:
A = np.array([
    [1, 0, 0, 1, 0, 0],
    [0, 0, 2, 0, 0, 1],
    [0, 0, 0, 2, 0, 0]
])
print(f"A = \n {A}")
# Transfomación de A en formato sparse comprimido por filas
S = csr_matrix(A)
print(f"A en formato sparse = \n {S}")

A = 
 [[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
A en formato sparse = 
   (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2


In [6]:
# Introducimos matrices en formato csr
row = np.array([0, 0, 1, 1, 2])
col = np.array([0, 3, 2, 5, 3])
data = np.array([1, 1, 2, 1, 1])
mtx = csr_matrix((data, (row, col)), shape=(3, 6))
print(f"Matriz en formate sparse = \n {mtx}")
# Transformamos a formato dense
B = mtx.todense()
print(f"mtx en formato dense = \n {B}")


Matriz en formate sparse = 
   (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	1
mtx en formato dense = 
 [[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 1 0 0]]


In [12]:
# Forma estandar de introducir una matriz sparse
print(f"Datos no nulos de la matriz mtx = {mtx.data}")
print(f"Indices de las columnas de mtx = {mtx.indices}")
print(f"Punteros para los indices de datos y columnas = {mtx.indptr}")
data = np.array([1, 1, 2, 1, 1])
ind_col = np.array([0, 3, 2, 5, 3])
puntero = np.array([0, 2, ])

Datos no nulos de la matriz mtx = [1 1 2 1 1]
Indices de las columnas de mtx = [0 3 2 5 3]
Punteros para los indices de datos y columnas = [0 2 4 5]


In [15]:
#Midiendo la dispersión de una matriz
def sparcity(A):
    spar = 1.0 - np.count_nonzero(A) / A.size
    return spar


<function __main__.sparcity(A)>