# Práctica 8. Factorizaciones LU, PLU y Choleski. Métodos directos de resolución de sistemas lineales

## Factorizaciones LU y PLU

Mediante la factorización $LU$ factorizamos una matriz $A$ en la forma $A=LU$, donde $L$ es una matriz triangular inferior y $U$ es triangular superior.

La factorización $PLU$, también llamada factorización $LU$ con pivoteo, es una ligera variante de la factorización $LU$, donde ahora la matriz $P$ es una matriz de permutación que permite ordenar las filas de $A$ para facilitar su factorización $LU$.
  

Más información en la [API del módulo de Álgebra Lineal de scipy](https://docs.scipy.org/doc/scipy/reference/linalg.html)

 



In [1]:
import numpy as np

Veamos un ejemplo concreto:

In [2]:
A = np.array(
    [[4, 3, -5],
    [-2, -4, 5],
    [8, 8, 0]]
    )

print(f"A = \n {A}")

from scipy.linalg import lu

P, L, U = lu(A)

print(f"P = \n  {P}")
print(f"L = \n {L}")
print(f"U = \n  {U}")

LU = np.dot(L, U)
print(f"LU = \n {LU}")

print(f"PLU = \n {np.dot(P, LU)}")


A = 
 [[ 4  3 -5]
 [-2 -4  5]
 [ 8  8  0]]
P = 
  [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L = 
 [[ 1.    0.    0.  ]
 [-0.25  1.    0.  ]
 [ 0.5   0.5   1.  ]]
U = 
  [[ 8.   8.   0. ]
 [ 0.  -2.   5. ]
 [ 0.   0.  -7.5]]
LU = 
 [[ 8.  8.  0.]
 [-2. -4.  5.]
 [ 4.  3. -5.]]
PLU = 
 [[ 4.  3. -5.]
 [-2. -4.  5.]
 [ 8.  8.  0.]]


In [3]:
# veamos el efecto de la matriz de permutación 
# (también llamada de pivoteo) P

print(np.dot(P, A))

[[ 8.  8.  0.]
 [-2. -4.  5.]
 [ 4.  3. -5.]]


## Factorización de Choleski

La factorización Choleski (también llamada factorización de Bunch-Kaufman) permite descomponer una matriz cuadrada $A$ en la forma $A = L D L^T$, donde $L$ es una matriz triangular inferior y $D$ es diagonal.

La factorización Choleski es especialmente eficaz (desde un punto de vista computacional) para el caso en que $A$ es simétrica y definida positiva.

Veamos un ejemplo concreto para las llamadas matrices de Toeplitz, las cuales aparecen habitualmente en varios campos de la Ingeniería

In [4]:

T = np.array([
    [2, -1, 0],
    [-1, 2, -1],
    [0, -1, 2]    
])

print(f"T = \n {T}")

from scipy.linalg import ldl

L, D, P = ldl(T) # P es una matriz de permutación

print(f"L = \n  {L}")
print(f"D = \n {D}")
print(f"P = \n  {P}")

LD = np.dot(L, D)
print(f"LD = \n {LD}")

print(f"LDL^T = \n {np.dot(LD, L.T)}")



T = 
 [[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]
L = 
  [[ 1.          0.          0.        ]
 [-0.5         1.          0.        ]
 [ 0.         -0.66666667  1.        ]]
D = 
 [[2.         0.         0.        ]
 [0.         1.5        0.        ]
 [0.         0.         1.33333333]]
P = 
  [0 1 2]
LD = 
 [[ 2.          0.          0.        ]
 [-1.          1.5         0.        ]
 [ 0.         -1.          1.33333333]]
LDL^T = 
 [[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  2.]]


## Métodos directos de resolución de sistemas lineales

Abordamos a continuación la resolución de sistemas lineales de la forma 
$Ax = b$, donde $A$ es una matriz cuadrada de orden $n$ y $b$ es un vector 
columna de $n$ componentes. La incógnita es $x$.

Para ello, utilizarmos el método [solve()](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.solve.html#scipy.linalg.solve), el cual usa las factorizaciones $LU$ y Choleski.
Todo ello aparece implementado en la librería [LAPACK](https://netlib.org/lapack/lug/)

Veamos un par de ejemplos

In [5]:
import numpy as np
from scipy.linalg import solve

A = np.array([
    [4, 3, -5],
    [-2, -4, 5],
    [8, 8, 0]
    ])
b = np.array([2, 5, -3])

x = solve(A, b)
print(f"x = {x}")

x = [ 2.20833333 -2.58333333 -0.18333333]


En el caso de que la matriz del sistema sea de una forma especial, por ejemplo 
simétrica y definida positiva, podemos indicar a *solve* que use una 
factorización adecuada al tipo de matriz.

In [6]:
import numpy as np
from scipy.linalg import solve

T = np.array([
    [2, -1, 0, 0, 0],
    [-1, 2, -1, 0, 0],
    [0, -1, 2, -1, 0],
    [0, 0, -1, 2, -1],
    [0, 0, 0, -1, 2]    
])

y = np.array([0, 0, -1, 0, 0])

# indicamos que la matriz es simétrica y definida positiva
x = solve(T, y, sym_pos='True') 
print(f"x = {x}")

x = [-0.5 -1.  -1.5 -1.  -0.5]
