# Práctica 4. Vectores: aritmética y normas 

In [1]:
import numpy as np

## Aritmética básica de vectores

In [2]:
# definimos dos vectores
a = np.array([1, 2, 3])
print(a)

b = np.array([1, 2, 3])
print(b)

# suma y resta
print(f"a + b  = {a + b}")
print(f"a - b  = {a - b}")


[1 2 3]
[1 2 3]
a + b  = [2 4 6]
a - b  = [0 0 0]


In [3]:
# multiplicación y división (componente a componente)
print(f"a * b = {a * b}")
print(f"a / b = {a / b}")

a * b = [1 4 9]
a / b = [1. 1. 1.]


In [4]:
# producto de un escalar por un vector
s = 0.5

print(f"s * a = {s * a}")

s * a = [0.5 1.  1.5]


In [5]:
# producto escalar de dos vectores (dot product en inglés)

print(f"a.b = {a.dot(b)}")

a.b = 14


In [6]:
# Repasamos todo con vectores de números complejos

z1 = np.array([1 + 1j, 1 -1j])
print(f"z1 = {z1}")
z2 = 1j * np.arange(2)
print(f"z2 = {z2}") 

print(f"z1 + z2  = {z1 + z2}")
print(f"z1 - z2  = {z1 - z2}")
print(f"z1 * z2  = {z1 * z2}")
print(f"z1 / z2  = {z1 / z2}")
s = 2j
print(f"s * z1 =  {s * z1}")
print(f"z1 . z2  = {z1.dot(z2)}")

z1 = [1.+1.j 1.-1.j]
z2 = [0.+0.j 0.+1.j]
z1 + z2  = [1.+1.j 1.+0.j]
z1 - z2  = [1.+1.j 1.-2.j]
z1 * z2  = [0.+0.j 1.+1.j]
z1 / z2  = [inf+infj -1. -1.j]
s * z1 =  [-2.+2.j  2.+2.j]
z1 . z2  = (1+1j)


C:\Users\fcoja\AppData\Local\Temp\ipykernel_21864\978379099.py:11: RuntimeWarning: divide by zero encountered in true_divide
  print(f"z1 / z2  = {z1 / z2}")


## [Normas de vectores](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.norm.html)

Tradicionalmente, norma de un vector $v = [v_1, \cdots, v_n]$ nos da una idea de la longitud de dicho 
vector. La norma euclídea, $\Vert v\Vert_2 = (\sum_{j=1}^nv_j^2)^{1/2}$ es 
ampliamente usada en Física con este propósito.

En Machine Learning, la norma euclídea también se usa a menudo para regularizar 
las llamadas **loss functions** (funciones de pérdida). Pero no es la única que 
se utiliza. De forma general, dados $v = [v_1, \cdots, v_n]\in\mathbb{R}^n$ y 
$1\leq p < \infty$, se define la norma $\Vert v\Vert_p = (\sum_{j=1}^nv_j^p)^{1/p}$.
Finalmente, $\Vert v\Vert_\infty = \max\left\{\vert v_j\vert, 1\leq j\leq n\right\}$.

Los casos más habituales son $p=1, 2, \infty$. Veamos cómo calcular estas normas.
El método norm() se encuentra en el submódulo linalg de numpy.


In [7]:
v = np.array([1, 2, 2])
print(a)

l2 = np.linalg.norm(v, 2) # norma 2
print(f"norma 2 de v = {l2}")

l1 = np.linalg.norm(v, 1) # norma 1
print(f"norma 1 de v = {l1}")

lmax = np.linalg.norm(v, np.inf) # norma del máximo o norma infinito
print(f"norma infinito de v = {lmax}")

[1 2 3]
norma 2 de v = 3.0
norma 1 de v = 5.0
norma infinito de v = 2.0
