# Práctica 2: Introducción a $n$-dimensional arrays en Python

In [27]:
import numpy as np

In [28]:
x = np.array([1,2,3])
print(x)
print(x.shape)
print(x.size)
print(type(x))
print(x.dtype)

[1 2 3]
(3,)
3
<class 'numpy.ndarray'>
int32


In [29]:
y = np.array([[1,2,3],
[4,5,6]])

print(y)
print(y.shape)
print(y.size)
print(type(y))
print(y.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
6
<class 'numpy.ndarray'>
int32


In [30]:
a = np.zeros([2,3])
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [31]:
b = np.ones([5])
print(b)

[1. 1. 1. 1. 1.]


In [32]:
c = np.arange(1, 10, 0.0005)
print(c)

[1.     1.0005 1.001  ... 9.9985 9.999  9.9995]


In [33]:
z = np.ones(4, dtype=complex) * 2
print(z)

[2.+0.j 2.+0.j 2.+0.j 2.+0.j]


In [40]:
a1 = np.array([1,2,3])
print(a1)
a2 = np.array([4,5,6])
print(a2)
a3 = np.vstack((a1, a2))
print(a3)
print(a3.shape)
a4 = np.hstack((a1, a2))
print(a4)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)
[1 2 3 4 5 6]


In [43]:
lista = [1,2,3]
print(lista)
print(type(lista))
vector = np.array((lista))
print(vector)
print(type(vector))

[1, 2, 3]
<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>


In [45]:
tupla = (1,2,3)
print(tupla)
print(type(tupla))

(1, 2, 3)
<class 'tuple'>
