# Práctica 6. Matrices sparse

In [4]:
import numpy as np
from scipy.sparse import csr_matrix

In [5]:
A = np.array([
    [1,0,0,1,0,0],
    [0,0,2,0,0,1],
    [0,0,0,2,0,0]
])
print(f"A = \n {A}")

A = 
 [[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


In [6]:
S = csr_matrix(A)

print(f"S = \n {S}")

S = 
   (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2


In [10]:
row = np.array([0,0,1,1,2])
col = np.array([0,3,2,5,3])
data = np.array([1,1,2,1,2])

mtx = csr_matrix((data, (row, col)), shape=(3,6))

print(f"Matriz sparse = \n {mtx}")

Matriz sparse = 
   (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2
