In [1]:
import numpy as np

In [3]:
A = np.array([
    [1,3,5],
    [7,9,11]
])
B = np.array([
    [0,2,4],
    [6,8,10]
])
print(f"A = {A}")
print(f"B = {B}")

A = [[ 1  3  5]
 [ 7  9 11]]
B = [[ 0  2  4]
 [ 6  8 10]]


In [4]:
# suma y resta
print(f"A + B = {A + B}")
print(f"A - B = {A - B}")

A + B = [[ 1  5  9]
 [13 17 21]]
A - B = [[1 1 1]
 [1 1 1]]


In [7]:
# producto de matrices
print(f"A.B = {A.dot(B.T)}")
print(f"A @ B = {A @ B.T}")

A.B = [[ 26  80]
 [ 62 224]]
A @ B = [[ 26  80]
 [ 62 224]]


In [8]:
# producto de Hadamard de matrices (componente a componente)
print(f"A * B \n = {A * B}")

A * B 
 = [[  0   6  20]
 [ 42  72 110]]
